### ISSUE TITLE
Can i change size of SDCAlertView?

### ISSUE THREAD

**Issue by DimonDeveloper** [sberrevoets/SDCAlertView#100]
I want to change the width of the alert in 2 times and transparency in about 20% it is possible to do it now?, or can you have a plan for this expense.

**Comment by sberrevoets** [comment]
You can use a custom `SDCAlertControllerVisualStyle` that overrides the `width` property to whatever you like. A different transparency is not possible due to the blur effect that functions as the background of the alert.

**Comment by DimonDeveloper** [comment]
Sorry for the stupid question, but I can not understand how to use SDCAlertControllerVisualStyle to change the width. 
I create class, than do like this:
 @interface SDCAlertControllerFileActionExistStyle : NSObject <SDCAlertControllerVisualStyle> and add all properties in .m file. 
Then do this: 
SDCAlertControllerFileActionExistStyle *FileActionStyle = [[SDCAlertControllerFileActionExistStyle alloc]init];
    SDCAlertController *alertController = [SDCAlertController alertControllerWithTitle:[NSString stringWithFormat:@"An item named \"%@\" already exists in this location",[self FileNameByPath:[ExistFiles objectAtIndex:0]]] message:@"What do you like to do?" preferredStyle:FileActionStyle]; But it not working.

**Comment by sberrevoets** [comment]
A visual style is different from the alert style. The alert style only determines whether you want to use the iOS 8 or iOS 7 style alert/presentation, whereas the visual style determines how the alert elements look.

You can define the visual style after initializing the alert by setting the `visualStyle` property like this:

```objc
SDCAlertControllerFileActionExistStyle *FileActionStyle = [[SDCAlertControllerFileActionExistStyle alloc]init];
SDCAlertController *alertController = [SDCAlertController alertControllerWithTitle:[NSString stringWithFormat:@"An item named \"%@\" already exists in this location",[self FileNameByPath:[ExistFiles objectAtIndex:0]]] message:@"What do you like to do?" preferredStyle:SDCAlertControllerStyleAlert];
alertController.visualStyle = FileActionStyle;
```

**Comment by DimonDeveloper** [comment]
Thank you very much, now everything works fine.
