### ISSUE TITLE
SDCAlertView did't callback actions, when all actions style == SDCAlertActionStyleDefault

### ISSUE THREAD

**Issue by Alex601t** [sberrevoets/SDCAlertView#104]
because if all actions style == SDCAlertActionStyleDefault, - (SDCAlertAction *)actionForButtonIndex:(NSInteger)buttonIndex inArray:(NSArray *)actions return nil action. So mb will add NSAssert for action style when alert being presented, and will add in method second condition —  

if (buttonIndex == self.cancelButtonIndex && cancelAction)
{
      return cancelAction;
}
else if(!cancelAction)
{
      return actions[buttonIndex];
}
else
{
      NSMutableArray *mutableActions = [actions mutableCopy];
      [mutableActions removeObject:cancelAction];
      return mutableActions[buttonIndex - 1];
}

**Comment by sberrevoets** [comment]
This was indeed a bug in version 2 of SDCAlertView. I just released version 3.0, which deprecates support for this altogether. I'm closing this issue, sorry I couldn't get to this.
