### ISSUE TITLE
[Question] How can I modify contentView position ?

### ISSUE THREAD

**Issue by rvi** [sberrevoets/SDCAlertView#106]
Hi,

I'm using `SDCAlertController`. I'm adding an image inside the contentView, it's working well.

I'd like the content view to be **before** the title and the message labels.

The contentView.frame.origin.x should be something like `0`. I tried to do it with `SDCAutoLayout` but it didn't work. 

Is it possible ?

Thanks.

**Comment by rvi** [comment]
Just submitted a pull request here : https://github.com/sberrevoets/SDCAlertView/pull/107

**Comment by sberrevoets** [comment]
I noted this in your PR as well, but for completeness sake: this functionality does not (and likely will not) exist. If you want this, I suggest you create 2 labels and add them to the `contentView` yourself.
