### ISSUE TITLE
There's no way to stop showing keyboard.

### ISSUE THREAD

**Issue by liroyan** [sberrevoets/SDCAlertView#108]
Because 
```c
		[self.textFields.firstObject becomeFirstResponder];
```
is called in - (void)viewDidLayoutSubviews and there's no way to turn it off.

Work around:
Disable textfield in addTextFieldWithConfigurationHandler, and then enable it in present completion block.

**Comment by sberrevoets** [comment]
That makes sense and I'd say that's the expected behavior. Why do you want to show a text field and not automatically focus on it?

**Comment by liroyan** [comment]
Per our PM's request, we want to show the alert so users could type in the email to subscribe something. But we don't want to pop up alert view together with a keyboard at the first time. Maybe a customizable api would be helpful, with default as YES.

**Comment by sberrevoets** [comment]
Sure, that should be manageable. I'm working on version 3.0, so I'll be sure to add some functionality for this in that version. I plan on releasing that around the same time iOS 9 is released, so until then I guess you'll have to use the workaround.

Thanks!

**Comment by liroyan** [comment]
Thanks!

**Comment by sberrevoets** [comment]
I just released version 3.0 which has support for this. Thanks for your patience!
