### ISSUE TITLE
UIKit not imported in SDCAlertControllerVisualStyle.

### ISSUE THREAD

**Issue by tapoton** [sberrevoets/SDCAlertView#110]
Since Xcode does not automatically create prefix header file with UIKit imported it becomes a problem.

**Comment by sberrevoets** [comment]
Thanks for bringing this up, I'll look at it myself and, if necessary, have a fix in shortly.

**Comment by sberrevoets** [comment]
I just released version 3.0 which doesn't have this problem anymore.
