### ISSUE TITLE
Unable to install WITHOUT cocoapods

### ISSUE THREAD

**Issue by kjmaior** [sberrevoets/SDCAlertView#115]
I cannot figure out how to get this to work without using CocoaPods (project is written in objective c).  I have this working with an older version 2.5.4 I believe.  Can you please provide instructions on how to do the installation without using CocoaPods?

Yes, I know CocoaPods are easy, however, I cannot use them in this project.

I have included all the files in the Source directory. I  removed SDCAutoLayout because that seems to be included in the source directory.  I still have RBBAnimation in my project.  I am getting errors such as...

 Value of type 'UIVisualEffectView' has no member 'sdc_alignEdges'

It seems like all the errors are related to referencing SDCAutoLayout.  I did try to include that in my project, outside of what is included in source directory, but no luck.  If I try to find the definition of this property it brings me to it in an objective c version of the SDCAutoLayout category.  When I try to find the definition of the same property in the example project, after installing the pod, it brings me to a swift file.

I feel like I am missing something.

I did try to grab the framework compiled with the sample project but that isn't working either.  App keeps crashing because it cannot find some image in the framework, which I thought was really weird!

**Comment by kjmaior** [comment]
Finally got it to install/compile.  I took the the framework, from DerivedData, after running the example project.  I had to import it, because it is a runtime library, as an embedded binary.  I then included the necessary header files.  The problem I am having now, and not sure if it is related to original problem of not being able to install without using CocoaPods is the alerts aren't showing up.

Even more interesting.  When I run the example project I am not seeing any alerts either after selecting what I want to see and hitting show.  I just see a shaded view being placed overtop the top most view.

Please advise.

**Comment by sberrevoets** [comment]
It sounds like you are missing an import in YourProject-Bridging-Header.h. This file is necessary if you want to use Objective-C in Swift files. Since SDCAutoLayout is still written in Objective-C, you'll need that header for SDCAlertView to recognize it.

Your findings when importing the framework directly are interesting. Would you mind posting the exact error you get when doing that?

**Comment by sberrevoets** [comment]
Someone else ran into the same issue of not seeing an alert, which is now fixed in 3.0.2. See https://github.com/sberrevoets/SDCAlertView/issues/116
