### ISSUE TITLE
Presentting the alert only dims the view in the demo

### ISSUE THREAD

**Issue by Sealos** [sberrevoets/SDCAlertView#116]
![screen shot 2015-10-19 at 15 24 52](https://cloud.githubusercontent.com/assets/4553825/10589574/d641d18e-7675-11e5-8a4e-f6fb2e8ce4a8.png)

**Comment by sberrevoets** [comment]
This was most definitely a bug, thanks for reporting. It's fixed in 3.0.2, which should now be available in CocoaPods.

**Comment by Sealos** [comment]
@sberrevoets thanks for the quick reply & fix!
