### ISSUE TITLE
Presenting the alert changes the status bar style

### ISSUE THREAD

**Issue by Sealos** [sberrevoets/SDCAlertView#117]
While having the UIViewControllerBasedStatusBarAppearance set to YES, presenting the alert doesn't sets the barStyle of the topViewController, so when it's presented it sets the default.

![screen shot 2015-10-20 at 09 38 03](https://cloud.githubusercontent.com/assets/4553825/10609621/5a97bf46-770e-11e5-82dc-5f827e50df3f.png)
![screen shot 2015-10-20 at 09 38 21](https://cloud.githubusercontent.com/assets/4553825/10609620/5a9720fe-770e-11e5-9cf2-a28929407d6b.png)

**Comment by sberrevoets** [comment]
Thanks, this should be resolved in https://github.com/sberrevoets/SDCAlertView/commit/e84a510430ee2af485ad86824fea6c4bbdbb1fd7
