### ISSUE TITLE
Add tvOS Cocoapods support

### ISSUE THREAD

**Issue by Jeehut** [sberrevoets/SDCAlertView#118]
I'd like to use this framework in a tvOS project using Cocoapods but in order to do this you need to explicitly state this project is made for tvOS, too.

For further details see [this blog post](http://blog.cocoapods.org/CocoaPods-0.39/).

**Comment by sberrevoets** [comment]
For that to work, I think it would first need to have some UI that makes sense on tvOS, right? I have not had a chance to take a look at that, so I don't know if adding tvOS support to just the pod spec will be enough.

**Comment by Dschee** [comment]
It actually didn't work out of the box in my case for my project. But I'm not sure if that's an issue with my project or this framework. I'll try to integrate manually via git submodules next and report how that went.

**Comment by Dschee** [comment]
That didn't work either. I am now removing SDCAlertView from my project. Seems there's need for more change to make this pod work with tvOS, just as @sberrevoets expected.

**Comment by sberrevoets** [comment]
I'm still not entirely sure what you're trying to do. Do you actually want to show an alert on tvOS, or do you just want the project to build without actually using it (on tvOS)?

**Comment by Dschee** [comment]
Well, at first I thought it might have been useful on tvOS, too. But in this specific project it isn't, so I don't want to show AlertViews any more.

But apart from that I feel it makes perfectly sense to show alert views on tvOS, too and it would make sense to have support for it so people can write frameworks that work both on iOS and tvOS.

**Comment by sberrevoets** [comment]
I agree, but I haven't yet had the chance to look at tvOS' capabilities, so I don't know if presenting an alert (and what it would look like) is even possible. A fix for just allowing it to build is fairly easy, but actually showing alerts will take some more time.

**Comment by Dschee** [comment]
Alerts are definitely available, though look quite different (e.g. they are full screen), see [here](https://developer.apple.com/tvos/human-interface-guidelines/ui-elements/#alerts) (Alerts section in the Apple TV Human Interface Guidelines).

**Comment by sberrevoets** [comment]
This doesn’t seem super important so closing the issue.
