### ISSUE TITLE
Crash when adding textfield on iOS 8.4

### ISSUE THREAD

**Issue by haseebq** [sberrevoets/SDCAlertView#124]
To reproduce the problem, create a SDCAlertController and add a textfield via addTextFieldWithConfigurationHandler. Run this on the iOS 8.4 simulator. 

Crash message:
Pods/SDCAlertView/Source/Text Fields/TextFieldsViewController.swift: 5: 7: fatal error: use of unimplemented initializer 'init(nibName:bundle:)' for class 'SDCAlertView.TextFieldsViewController'

**Comment by sberrevoets** [comment]
Ah, apparently iOS 8 wasn't a fan of `UITableViewController` subclasses in Swift. This is fixed in 3.0.4 (just released). Thanks for reporting!
