### ISSUE TITLE
Message is not being padding appropriately

### ISSUE THREAD

**Issue by Nikian** [sberrevoets/SDCAlertView#126]
When I set some decently long text as the AlertController message, it appears to be missing its left and right padding. I haven't been able to resolve this with setVisualStyle.

![simulator screen shot nov 27 2015 11 22 30 pm](https://cloud.githubusercontent.com/assets/4421713/11450089/11eb0884-955e-11e5-905b-4bd2cecab2fe.png)

**Comment by sberrevoets** [comment]
Yeah that's being talked about here as well: https://github.com/sberrevoets/SDCAlertView/pull/123

I'm going to close this as a duplicate, feel free to join the conversation over there.
