### ISSUE TITLE
LayoutConstraint Error after rotation

### ISSUE THREAD

**Issue by mohpor** [sberrevoets/SDCAlertView#134]
Hi,

I have an alert view containing textfields. when text fields are first responder, if a rotation happens it will complaint that it can't simultaneously satisfy some constraints with action view collection and a scroll view.

I have narrowed it down to the line of code producing this error and commented it out.
Not only it fixed the warning, it has fixed another issue related to actions not being visible after rotation + keyboard. (content will scroll but actions are gone)

I wish I could find the time to make a decent PR, but for now, in ``

```swift
 private func createScrollViewConstraints() {
        self.scrollView.sdc_alignEdges([.Left, .Right, .Top], withView: self)
        self.scrollView.layoutIfNeeded()
//        self.scrollView.sdc_pinHeight(self.scrollView.contentSize.height)
    }
```

P.S: we are already pinning all edges of the scroll view. We don't need to ping the height too.

**Comment by sberrevoets** [comment]
That does seem like a bug. I'll investigate this a little more and will issue a fix if necessary. Thanks for letting me know.

**Comment by sberrevoets** [comment]
I think d8a51dab2df701e49a94f76227305382e3678ba3 fixes the problem, could you double-check and report back so I can release this?
