### ISSUE TITLE
Please add ability to set background color for action

### ISSUE THREAD

**Issue by larryonoff** [sberrevoets/SDCAlertView#136]
I can create PR for this.

**Comment by sberrevoets** [comment]
Feel free to open a PR. I'm not sure when I'll get to it.

**Comment by sberrevoets** [comment]
PR for this here: https://github.com/sberrevoets/SDCAlertView/pull/138

**Comment by gchiacchio** [comment]
I'm also interested in having a different background color for actions. There is any workaround to accomplish this without the PR?

**Comment by sberrevoets** [comment]
Couldn't you use the functionality that was added in that PR?

**Comment by gchiacchio** [comment]
@sberrevoets I thought it was not merged yet. Waiting for some update for part of @larryonoff .
Can you confirm that?

**Comment by sberrevoets** [comment]
Oh yeah, my bad. That PR wasn't quite ready to be merged yet so I guess that functionality is not in there now. Unfortunately I don't know of a workaround off the top of my head. If you want to finish the PR (I think the suggestions were fairly easy) then feel free to. I'm a bit busy at the moment so not sure I'll be able to get to it myself soon.

**Comment by larryonoff** [comment]
I wasn't able updating PR according to the request, so this was closed. As far as I remember there weren't a lot to do. So feel free updating my PR.
