### ISSUE TITLE
Touches on custom content view delayed

### ISSUE THREAD

**Issue by osrl** [sberrevoets/SDCAlertView#140]
When I use custom content view, touches are delayed. I need to long press any item to trigger action. Did I miss something?

**Comment by sberrevoets** [comment]
What sort of action are you talking about?

**Comment by osrl** [comment]
I've loaded a ViewController from xib and added its view to the contentView. There are buttons and a slider in the xib. All views have to be long pressed to be controlled. I can't slide the slider without long pressing the thumb for example.
        
        let title = "title"
        let message = "message"
        let style = AlertControllerStyle.Alert
        let alert = AlertController(title: title, message: message, preferredStyle: style)

        let contentView = alert.contentView
        let myViewController = MyViewController(nibName: "MyViewController", bundle: nil)
        let view = myViewController.view
        view.translatesAutoresizingMaskIntoConstraints = false
        contentView.addSubview(view)

        view.centerXAnchor.constraintEqualToAnchor(contentView.centerXAnchor).active = true
        view.topAnchor.constraintEqualToAnchor(contentView.topAnchor).active = true
        view.bottomAnchor.constraintEqualToAnchor(contentView.bottomAnchor).active = true
        view.leftAnchor.constraintEqualToAnchor(contentView.leftAnchor).active = true
        view.rightAnchor.constraintEqualToAnchor(contentView.rightAnchor).active = true

**Comment by sberrevoets** [comment]
Ah that makes sense as `delaysContentTouches` is set to `true` by default, even if there is nothing to scroll. One solution could be to check if the scroll view actually scrolls (which it can't in most cases), and only set `delaysContentTouches` to true if it does. This is fairly tricky as it needs to consider rotation and content size changes.

Feel free to submit a PR if you want, otherwise I'll get to it at some point.

**Comment by sberrevoets** [comment]
More than a year later, but I just pushed a branch that potentially has a fix: https://github.com/sberrevoets/SDCAlertView/tree/fix-delay

Can you double-check this works for you (if you still need it)?

**Comment by sberrevoets** [comment]
Let me know if this is still relevant!
