### ISSUE TITLE
ViewController doesn't resize after in call status bar disappear

### ISSUE THREAD

**Issue by amarcadet** [sberrevoets/SDCAlertView#143]
When I enable in-call status bar (⌘Y) the view of the view controller is resized correctly but when I disable the in-call status bar the view does not move to its original frame, leaving an empty space without overlay exposed.

See screenshot below: 
![screenshot](https://infinit.io/_/DK6PmWF.png)

Reproduced on device on iOS 9 and simulator iOS 8 and 9.

**Comment by sberrevoets** [comment]
You're right, it looks the same as this bug: http://stackoverflow.com/questions/25882609/how-to-do-layout-to-handle-in-call-double-height-status-bar-for-custom-present

The answer there is a major (very fragile) hack that I'd rather not employ for what is likely an edge case. Please let me know if you can think of a better solution, but I'm gonna close this as a "won't fix" for now.

**Comment by amarcadet** [comment]
I found a workaround that can be done in the app delegate, so you don't have to introduce hack in your codebase.

I paste it below in case someone else is interested in fixing this bug. I tried different values for the animation duration and `0.35` was looking good. Hope this could help, but this is indeed an **ugly workaround**.

```swift
func application(application: UIApplication, willChangeStatusBarFrame newStatusBarFrame: CGRect) {
    // fix https://github.com/sberrevoets/SDCAlertView/issues/143
    if let window = self.window where newStatusBarFrame.size.height < 40 {
        UIView.animateWithDuration(0.35, animations: {
            window.subviews.forEach({ $0.frame = window.bounds })
        })
    }
}
```

Side note: I haven't published my app to the store yet but I don't see any use of private API, so it should be ok.

**Comment by SaadIEng** [comment]
@amarcadet obj-c implementation of this plz
