### ISSUE TITLE
Make visual style more easily configurable

### ISSUE THREAD

**Issue by gereons** [sberrevoets/SDCAlertView#144]
Maybe I'm missing something obvious here, but I can't figure out how to change minor things in the DefaultVisualStyle.

In my current project, I simply want to change the alert's background color, and had hoped to be able to do

    class MyVisualStyle: DefaultVisualStyle {
        var backgroundColor: UIColor? {
            return UIColor.whiteColor()
        }
    }

but that doesn't work. Implementing the full VisualStyle protocol doesn't seem to work either, since AlertController.visualStyle is of type `DefaultVisualStyle`.

**Comment by sberrevoets** [comment]
What you're trying to do should work. If it doesn't, that's a bug. The default blur background looks a lot like white in the Example project - is that what you're trying this on? Do you see a difference if you change it to, say, green?

Also, just to make sure we're talking about the same thing: the background color changes the background of the alert itself, not the dimmed background that overlays previous content.

**Comment by gereons** [comment]
Yes, I'm talking about the alert's background, and yes, I'm sure my "override" isn't called - I added NSLogs and breakpoints, both weren't hit.

**Comment by sberrevoets** [comment]
Interesting. I'll look into this. Thanks for reporting!

**Comment by sberrevoets** [comment]
Taking this discussion to #145.
