### ISSUE TITLE
Alternative to constraints for setting height

### ISSUE THREAD

**Issue by jrl290** [sberrevoets/SDCAlertView#147]
I'm afraid constraints are just too difficult to work with. In my particular instance, I've been loading a UIView from an xib containing 6 subviews, and using every variation of,

spinner.translatesAutoresizingMaskIntoConstraints = false
spinner.centerXAnchor.constraintEqualToAnchor(alert.contentView.centerXAnchor).active = true
spinner.topAnchor.constraintEqualToAnchor(alert.contentView.topAnchor).active = true
spinner.bottomAnchor.constraintEqualToAnchor(alert.contentView.bottomAnchor).active = true

...I could find, I still could not get the right height.

Could I suggest either a simple height property? Or alternatively, the ability to build the contentView directly in IB?

Thanks so much!

**Comment by sberrevoets** [comment]
There probably is some combination of constraints that would make it work, but I agree dealing with XIBs isn't always easy.

A `height` property doesn't seem ideal as then you can have conflicting heights which doesn't make it any easier to understand, but I can be convinced of adding a `setContentViewWithXIB()`-like method. It would then internally create the right constraints and you wouldn't have to deal with it when creating an alert.

**Comment by jrl290** [comment]
That is an excellent idea!

**Comment by SchmidtyApps** [comment]
@sberrevoets Along the lines of the height of custom content heights, if in the ActionSheetView xib the constraint from title label baseline to superview were set to have a priority of 250 any custom views added to the content view(pinned to top and bottom) would auto size as long as they were laid out similar to how you would layout a xib for autosizing table view cells. Right now the default title/message labels block the added custom view from determining its own height unless a height constraint is applied to the custom view like in your example? With this change the intrinsic content size would automatically set the height for the contentView. Thoughts? Id be happy to do a pull request if you will approve it.

**Comment by sberrevoets** [comment]
As long as nothing relies on that constraint being higher than 250 (which I don't think is the case), that sounds like a reasonable change to me, yes 👍

**Comment by SchmidtyApps** [comment]
Made that priority change and added a custom view init that adds the constraints automatically per the conversation above. It actually looks like it fixed padding issues with the example app's custom views as well so bonus win! 😜

https://github.com/sberrevoets/SDCAlertView/pull/241

**Comment by sberrevoets** [comment]
Closing this since the original PR was closed as well
