### ISSUE TITLE
Functions in AlertAction handler are not called if the AlertAction does not make the alert controller dismiss

### ISSUE THREAD

**Issue by allNewNewbie** [sberrevoets/SDCAlertView#154]
I made an alert controller by the following code:

`
let alert = AlertController(title: "Title", message: "This is a message")
alert.addAction(AlertAction(title: "Dismiss", style: .Default))
alert.addTextFieldWithConfigurationHandler()

let sendAction = AlertAction(title: "Send", style: .Default, handler: { (sendAction) in
    print("\(alert.textFields![0].text)")
    print("Send")
})
alert.addAction(sendAction)
alert.present()
`

I wished the value in the textfield can be processed without dismissing after the sendAction button was taped.  However, the functions are not called.  Is it possible to achieve this behavior?

Thank you!

**Comment by sberrevoets** [comment]
Which functions aren't called?

I believe you can do this by setting the `shouldDismissHandler` on `AlertController`. In there you'd check `alert.textFields.first` or something like that and return `false` if you don't want the alert to be dismissed. Is that what you're looking for?

**Comment by allNewNewbie** [comment]
Thanks for your reply.  I got it!!

I was wondering why the two "print" functions in the handler closure of sendAction were never called.  Now I understand that the functions which are to be called should be placed in the `shouldDismissHandler` closure.

I had `alert.shouldDismissHandler = {$0!.title == "Dismiss"}` before `alert.present()` in my code, but I forgot pasting it in my last post.  Now I modified my `shouldDismissHandler` closure as follows.

alert.shouldDismissHandler = {
                        
                            if $0!.title == "Dismiss" {
                                return true
                            }
                            else if $0!.title == "Send" {
                                print("\(alert.textFields![0].text)")
                                print("Send")
                                return false
                            }
                            else {
                                return true
                            }
                            
                        }

and everything seems working fine now.

Thank you!

**Comment by sberrevoets** [comment]
Glad you were able to figure it out!
