### ISSUE TITLE
When action text is too long

### ISSUE THREAD

**Issue by namanhams** [sberrevoets/SDCAlertView#159]
Hi,

This library is awesome, but i encounter an issue : if the action happens to be too long (2 lines), then it will not be displayed properly. We should allow more than 1 line here or at least trim the text.

Is there any work-around for this ?

**Comment by sberrevoets** [comment]
When you say "will not be displayed properly", what do you mean? Can you post a screenshot?

**Comment by namanhams** [comment]
Hey sorry for my late reply. Here's the attached screenshot: 

![simulator screen shot 8 aug 2016 11 34 41 am](https://cloud.githubusercontent.com/assets/327032/17468544/755d3b74-5d5b-11e6-87f8-9a04f85a217d.png)

**Comment by sberrevoets** [comment]
Yeah, the text should be trimmed there since that's what `UIAlertController` does. Feel free to submit a PR if you're interested in fixing this!

**Comment by namanhams** [comment]
Thanks! I'll try.

**Comment by sberrevoets** [comment]
@namanhams This is fixed in a2766c58fcd057c84a21558a54cbe996616ef3fc.

I will release an update containing this fix soon.

**Comment by sberrevoets** [comment]
I just released 7.1 which includes this fix.
