### ISSUE TITLE
Swift 2.2 and XCode 8 compatibility

### ISSUE THREAD

**Issue by brbsBruno** [sberrevoets/SDCAlertView#162]
Hello, 
congratulations for the work you have been developing.

I have being using your library and faced some issues swift 2.2 and XCode 8 compatibility.
After doing some [digging](http://stackoverflow.com/questions/37835397/use-swift-2-2-in-xcode-8), I've found that this library must be migrated at least to version 2.3.

So, as I could see, you already worked on this issue in another branch, and I just want to know if you have any plans about merging this into master any time soon. (Today I integrate your lib throw Cocoapods)

So many thanks. 😊

**Comment by sberrevoets** [comment]
Yes, Swift 2.3 support will be in master right around September 7 in a new major version (6.0). Then shortly after that I will also merge Swift 3 support into master with again a major version change (7.0).

If you are not quite ready to migrate to Swift 3 at that point you'll have to specify 6.0 in your Podfile to make sure everything still builds.

Until September 7, I recommend specifying `swift-2.3` in your Podfile.

**Comment by brbsBruno** [comment]
Thank you for fast response!

I'll leave in here the podfile snipped that will do this trick, in case someone else stumble in this issue.

```ruby
post_install do |installer|
  sdcAlertView = installer.pods_project.targets.find { |target| target.name == 'SDCAlertView' }
  sdcAlertView.build_configurations.each do |config|
    config.build_settings['SWIFT_VERSION'] = "2.3"
  end
end
```

**Comment by sberrevoets** [comment]
Thanks!
