### ISSUE TITLE
Swift 2.3 / 3 Support

### ISSUE THREAD

**Issue by twiedow** [sberrevoets/SDCAlertView#164]
Hi,

I just like to know how your plans are about releasing a Swift 2.3 / Swift 3 compatible version?

Thanks,

Tobi

**Comment by sberrevoets** [comment]
There will be 2 major version updates soon. The first one (6.0) is just for Swift 2.3 compatibility. The second one (7.0) will be for Swift 3 and that is where further development will happen. Expect these to be released soon.

In the meantime, you can use the `swift-2.3` and `swift-3` branches.

**Comment by swmoon203** [comment]
I made little change to support swift 3
https://github.com/swmoon203/SDCAlertView/tree/swift3

**Comment by sberrevoets** [comment]
Thanks! I actually just pushed to the `swift-3` branch as well so it now builds with the Xcode 8 GM.

**Comment by sberrevoets** [comment]
I've released 2 major versions now: 6.0 for Swift 2.3 and 7.0 for Swift 3. Let me know if there are any problems!

**Comment by happiehappie** [comment]
Just wondering, doesn't anyone has buildtime issue with swift 2.3?

**Comment by Saurman** [comment]
I have

**Comment by sberrevoets** [comment]
I just checked out the `v6.0` tag and everything builds fine. Can you open a separate issue describing the exact problem you have?
