### ISSUE TITLE
Pull request of queue mechanism for alertviewcontroller

### ISSUE THREAD

**Issue by liheyuan** [sberrevoets/SDCAlertView#165]
Hello, 

I have made a pull request for queue mechanism last week.

https://github.com/sberrevoets/SDCAlertView/pull/163

However, it remains un-merged, nor do I receive any comment.

Is there some steps I was missing for pull request?

Thank you.

**Comment by sberrevoets** [comment]
Sorry it took a while to get back to you on this, let's move the discussion to your PR.
