### ISSUE TITLE
Swift 3 AlertController access level

### ISSUE THREAD

**Issue by johntvolk** [sberrevoets/SDCAlertView#166]
Hi,

Up until now, my method of incorporating SDCAlertView into my app has been to subclass AlertController as a convenient place to put all my alert related state. The new access level stuff in Swift 3 has been preventing that. Basically, AlertController would need to be `open` rather than `public`. Does this fit with your vision for this library, or should I refactor to composing an AlertController rather than inheriting? Thanks.

**Comment by sberrevoets** [comment]
First of all, thanks for bringing this up!

I think "composition over inheritance" applies here a lot. Subclassing has become more and more something to avoid, and while it's not always possible, I think this is a case where I would favor composition over inheritance.

If you needed to actually override some things in `AlertController` then we could look at what that is, why, and possibly `open` it up. In this case, I'd rather avoid doing so.

Let me know if you have any questions/concerns around this.

Thanks again!

**Comment by johntvolk** [comment]
Thanks for your reply. I've switched over to composition.

I now have a FooAlert class that manages an instance of AlertController. My actual controller builds an instance of FooAlert and then FooAlert presents it's AlertController. One thing I noticed that was nicer about the subclass setup was that UIKit would implicitly keep my Alert class in memory by placing it in the view hierarchy. Now that I've moved to composition my FooAlert class needs to be explicitly referenced as an instance var of my main controller to prevent deallocation during async events (network, etc.). Do you have any common pattern you use for dealing with this issue? Thanks.

- John

**Comment by sberrevoets** [comment]
I'm not entirely sure why you'd want `FooAlert` to stay around for the controller to talk to. Could you give me an example of something you're trying to do that is more difficult without the ability to subclass?

**Comment by johntvolk** [comment]
Sure, let me try to explain it better.

In my project I'm using SDCAlertView (AlertController) to show a UI for a multi-file upload process. Roughly, it looks like this. Let's say my main controller is called FooController and it has a list of files that it wants to upload. The network / UI logic for this upload is somewhat involved so it's something I'd like to have live in it's own class. To accomplish this, I now have a class called UploadAlert. This class is responsible for configuring and presenting an AlertController, kicking off each upload request, and then updating the UI in that AlertController as each upload completes. To do this it has references to the UIProgressView / etc that have been placed in the contentView of the AlertController.

The problem is that since this new UploadAlert isn't in the UIWindow's view hierarchy (it's not a view controller) it will be deallocated after the initial async network request is kicked off. When the request completes, self is nil, so I can't update the UI.

The way I've solved this for now is to have FooController maintain a reference to UploadAlert, so it stays in memory. I didn't used to have this problem when all my logic lived in an AlertController subclass, because it would be retained by virtue of being in the view hierarchy.

It occurs to me now that I could have my async callback closure in UploadAlert strongly capture self in order to keep UploadAlert in memory, but I usually try to avoid solving things with circular references like that.

Anyways, not a huge issue, I just wondered if you had any ways you typically deal with this kind of thing. Hope that all makes sense.

**Comment by sberrevoets** [comment]
I see how not subclassing makes this a bit more difficult, but referencing the single responsibility principle I think it makes sense to _not_ subclass and add a bunch of things that are unrelated to an alert. I'm not sure what would be the proper architecture, but in your case I think holding on to `UploadAlert` is better than tacking it to a class whose responsibility it is to present an alert.
