### ISSUE TITLE
Crashing when I try to create a sheet

### ISSUE THREAD

**Issue by Kennouf** [sberrevoets/SDCAlertView#168]
When I use `[SDCAlertController sheetWithTitle:@"Title" message:@"Message" actions:@[@"OK"]]` I get a crash in `assignCancelAction()` : last line `self.actions.removeFirst()` makes the project crash with this message : 

fatal error: can't remove first element from an empty collection

Same when I use `[[SDCAlertController alloc] initWithTitle:@"Title" message:@"Message" preferredStyle:SDCAlertControllerStyleActionSheet];` and afterwards try to use the `add:`method

**Comment by sberrevoets** [comment]
Oops, sorry about that. 7.0.1 should fix your issue.

**Comment by Kennouf** [comment]
Thanks man, it doesn't crash anymore. I have another question though : how is the cancel action supposed to work ? It doesn't seem to delete the action that is set for cancel, it copies it instead (I have Option 1, Option 2, Cancel, a space and Cancel again)

**Comment by sberrevoets** [comment]
It's _supposed_ to remove the cancel action if none is explicitly set. The call to `removeFirst()` there is what caused the crash at first, so it seems like it gets called at least. Will take a look again.
