### ISSUE TITLE
Can't inherit new class from AlertViewController in Swift 3.0

### ISSUE THREAD

**Issue by Den-Ree** [sberrevoets/SDCAlertView#171]
Hi, I can't inherit new class from AlertViewController in Swift 3.0, do you know how to fix it?

**Comment by sberrevoets** [comment]
This is more or less intended. See https://github.com/sberrevoets/SDCAlertView/issues/166 for some discussion on this.

**Comment by Den-Ree** [comment]
@sberrevoets thanks, I got it.
