### ISSUE TITLE
Readme is not up to date with Framework code for Swift 3

### ISSUE THREAD

**Issue by racer1988** [sberrevoets/SDCAlertView#174]
Examples:

     alert.addAction(notNowAction)

should be

    alert.add(notNowAction)

due to API being now:

    public func add(_ action: SDCAlertView.AlertAction)

**Comment by sberrevoets** [comment]
Yes, thanks for bringing this up. Feel free to submit a PR if you want, otherwise I'll take this on soon.

**Comment by sberrevoets** [comment]
Actually, just updated the README. Let me know if you see any problems!

**Comment by racer1988** [comment]
Thanks! 
sorry I was unable to make a PR for it and then i forgot 🙃
