### ISSUE TITLE
xcodebuilld warning: cannot open project

### ISSUE THREAD

**Issue by racer1988** [sberrevoets/SDCAlertView#175]
Just a Warning happening while building with Carthage.
Does not happen with other frameworks using playgrounds, so may be useful to move the playground in a Example folder instead or create a Example project to separate them

xcodebuild: WARNING: Unable to open project file '/bla/Carthage/Checkouts/SDCAlertView/Example.playground' in workspace '/bla/Carthage/Checkouts/SDCAlertView/SDCAlertView.xcworkspace'

**Comment by sberrevoets** [comment]
Thanks for reporting this @racer1988! It appears that [RxSwift](https://github.com/ReactiveX/RxSwift/issues/856) was having the same problem without resolution. I tend to agree that since this appears to be a bug (?) in Carthage, this is something that should be fixed there. Since it's not an error I'd rather not remove the playground from the project altogether.

It is interesting however that you are using other frameworks with playgrounds. Can you provide an example of a framework where this doesn't happen?

**Comment by racer1988** [comment]
Hi @sberrevoets!

I actually found one framework that I use with Carthage and Playground, that does not trigger any build issue, so I believe it is a scheme/folder structure issue in your project settings?

Examples with no build issue and Playground in the Example folder:
https://github.com/SwiftyJSON/SwiftyJSON/tree/master/Example/Playground.playground

**Comment by sberrevoets** [comment]
I'll take a look, thank you!

**Comment by sberrevoets** [comment]
Hey @racer1988, this should be fixed as of 0803e362422a7655951e398e56fbc607c1606e43.

I will release a new version containing this fix soon.

**Comment by sberrevoets** [comment]
This was fixed as part of 7.1, thanks again for bringing this up!

**Comment by verticon** [comment]
@sberrevoets I am experiencing this same issue with a Carthage build of a GitHub project that I am working on. Would you please be so kind as to share what you did to eliminate the xcodebuild warning?

**Comment by sberrevoets** [comment]
Yes, I simply removed the playground. I think I reached the conclusion that this was a bug in the tooling (either Xcode or Carthage), but that the playground wasn't very useful anyway.

**Comment by verticon** [comment]
Thank you, Scott. I am still pursuing it. If I get a resolution then I'll circle back around and and let you know.

**Comment by verticon** [comment]
Hey Scott, [Here](https://github.com/Carthage/Carthage/issues/1728) is what the Carthage folks had to say. Good luck with your projects.

**Comment by sberrevoets** [comment]
Thanks for following up!
