### ISSUE TITLE
Can't interact with subview

### ISSUE THREAD

**Issue by edenfisher** [sberrevoets/SDCAlertView#178]
Hey,
I've added a simple view which is a rating view(5 stars that you can click on-HCSStarRatingView).
Unfortunately, the view is not clickable so I cant interact with it.
I've added the subview to the contentVIew, try to create it with the convenience method and even tried to call bringSubviewTofront but nothing helps.
What seems to be the problem?
 Thank you

**Comment by sberrevoets** [comment]
That's not expected, you should be able to interact with views in the `contentView`. Can you post the code that builds the alert?

**Comment by cguerra-externo-technisys** [comment]
Sorry for put something here, but I got the same problem, this a short part of my code:
let alert = AlertController(title: WIBEHelpers.findString("coolDrive.autostart"), message: WIBEHelpers.findString("coolDrive.autostart.dialog.Info"))
            
            let cancel = AlertAction(title: WIBEHelpers.findString("coolDrive.dialog.cancel"), style: .Preferred) { (result : AlertAction) -> Void in
                alert.dismissViewControllerAnimated(false, completion: nil)
            }
            
            let accept = AlertAction(title: WIBEHelpers.findString("coolDrive.dialog.accept"), style: .Default) { (result : AlertAction) -> Void in
                alert.dismissViewControllerAnimated(false, completion: nil)
            }
            
            let showAgainBtn = UIButton(type: .Custom)
            showAgainBtn.setImage(WIBEHelpers.getImage("wibe_chack_inactivo"), forState: .Normal)
            showAgainBtn.setImage(WIBEHelpers.getImage("wibe_check_activo"), forState: .Selected)
            showAgainBtn.addTarget(self, action: #selector(showAgainTap(_:)), forControlEvents: .TouchUpInside)
            showAgainBtn.translatesAutoresizingMaskIntoConstraints = false
            
            
            alert.contentView.addSubview(showAgainBtn)
            alert.addAction(cancel)
            alert.addAction(accept)
            
            let contentView = alert.contentView
            let switchControl = UISwitch()
            switchControl.on = true
            switchControl.translatesAutoresizingMaskIntoConstraints = false
            contentView.addSubview(switchControl)
            
            alert.shouldDismissHandler = { [unowned switchControl] _ in
                return switchControl.on
            }
            
            constrain(alert.contentView){ container in
                container.height == 50
            }
            
            constrain(showAgainBtn, alert.contentView){ button, container in
                button.height == 25
                button.width == 25
                button.leading == container.leading
                button.top == container.top - 25
            }
            
            constrain(switchControl, showAgainBtn){ switchC, button in
                switchC.leading == button.trailing + 10
                switchC.top == button.top
            }

            alert.present()

**Comment by edenfisher** [comment]
`        let ratingStars = HCSStarRatingView(frame: CGRect(x: 28, y: -40, w: 180, h: 30))
        ratingStars.minimumValue = 0
        ratingStars.maximumValue = 5
        ratingStars.value = 0
        ratingStars.backgroundColor = UIColor.clearColor()
        
        let alert = AlertController.alertWithTitle("How was today's Challange?", message: nil, actionTitle: "OK", customView: ratingStars)`
Also tried without the convenience method and no good

**Comment by sberrevoets** [comment]
Thanks. Feel free to submit a PR if you understand what the problem is. Otherwise I'll take a look at it hopefully soon.

**Comment by edenfisher** [comment]
I think maybe my customView is placed out of the frame of the contentView. I'm investigating it right now.

**Comment by sberrevoets** [comment]
Does it work if you do `ratingStars.translatesAutoresizingMaskIntoConstraints = false`?

**Comment by edenfisher** [comment]
Hey, I used the answer there: https://github.com/sberrevoets/SDCAlertView/issues/132
to solve my issue. Just added some constraints so the contentView has size and added 
ratingStars.translatesAutoresizingMaskIntoConstraints = false
Thats it.
Working code:
`        let ratingStars = HCSStarRatingView(frame: CGRect(x: 28, y: -40, w: 180, h: 30))
        ratingStars.minimumValue = 0
        ratingStars.maximumValue = 5
        ratingStars.value = 0
        ratingStars.backgroundColor = UIColor.clearColor()
        ratingStars.translatesAutoresizingMaskIntoConstraints = false
        
        let alert = AlertController(title: "How was today's Challange?", message: "\n")
        alert.contentView.addSubview(ratingStars)
        alert.contentView.addConstraint(NSLayoutConstraint(item: ratingStars, attribute: NSLayoutAttribute.Top, relatedBy: NSLayoutRelation.Equal, toItem: alert.contentView, attribute: NSLayoutAttribute.Top, multiplier: 1.0, constant: 0.0))
        alert.contentView.addConstraint(NSLayoutConstraint(item: ratingStars, attribute: NSLayoutAttribute.Left, relatedBy: NSLayoutRelation.Equal, toItem: alert.contentView, attribute: NSLayoutAttribute.Left, multiplier: 1.0, constant: 0.0))
        
        alert.contentView.addConstraint(NSLayoutConstraint(item: ratingStars, attribute: NSLayoutAttribute.Right, relatedBy: NSLayoutRelation.Equal, toItem: alert.contentView, attribute: NSLayoutAttribute.Right, multiplier: 1.0, constant: 0.0))
        alert.contentView.addConstraint(NSLayoutConstraint(item: ratingStars, attribute: NSLayoutAttribute.Height, relatedBy: NSLayoutRelation.Equal, toItem: nil, attribute: NSLayoutAttribute.Height, multiplier: 1.0, constant: 120.0))
        alert.contentView.addConstraint(NSLayoutConstraint(item: alert.contentView, attribute: NSLayoutAttribute.Bottom, relatedBy: NSLayoutRelation.Equal, toItem: ratingStars, attribute: NSLayoutAttribute.Bottom, multiplier: 1.0, constant: 0.0))
        alert.contentView.invalidateIntrinsicContentSize()
        let cancel = AlertAction(title: "No thanks", style: .Preferred) { (result : AlertAction) -> Void in
            alert.dismissViewControllerAnimated(false, completion: nil)
        }
        
        let accept = AlertAction(title: "Ok", style: .Default) { (result : AlertAction) -> Void in
            alert.dismissViewControllerAnimated(false, completion: nil)
        }
        alert.addAction(cancel)
        alert.addAction(accept)
        alert.present()`
