### ISSUE TITLE
Alert dismiss animation

### ISSUE THREAD

**Issue by timautin** [sberrevoets/SDCAlertView#181]
The dismiss animation is not the same as UIAlertView's, nor the one we can see here:

<img src="https://camo.githubusercontent.com/cf53154ecc3adafcd7b664e8cbc64f7448c964b5/687474703a2f2f736265727265766f6574732e6769746875622e696f2f534443416c657274566965772f416c6572742e676966"/>

Instead of being faded out, the alert is dismissed by sliding from top to bottom. Is it normal? If so, do you intend to fix it?

I'm using version 7.0.1 and Swift 3. Problem happens on iOS 8 & 10. I had to use Xcode's convert to current swift syntax tool to be able to compile and run.

Thanks

**Comment by sberrevoets** [comment]
Thanks for catching this, looks like this is something that went wrong in the migration to Swift 3. Someone else just submitted a PR for this: https://github.com/sberrevoets/SDCAlertView/pull/183.

I'm closing this so we can take further discussion there.

**Comment by timautin** [comment]
OK you're right, that's certainly the problem! I could have thought to it, because I ran into the exact same issue a few days ago with a custom controller after migrating my code. Thanks Xcode, once again...

**Comment by sberrevoets** [comment]
Interesting. Could you open a new issue (or even better, a PR 💃) highlighting the before and after and the UIAlertController version to compare to?
