### ISSUE TITLE
Background is not as bright as iOS

### ISSUE THREAD

**Issue by timautin** [sberrevoets/SDCAlertView#184]
The default iOS popup background is brighter than the one of SDCAlertView. It might not be possible to get the exact same effect though (without doing your own blur effect), as neither light nor extraLight blur effects are the one used by UIAlertController.

**Comment by sberrevoets** [comment]
Yeah it's pretty much impossible to get to the exact same solution. Apple uses a private class that uses private CI filters to create the exact effect of their alerts. Doesn't seem worth to reverse engineer, but if you want to learn more about Core Image this would be a great opportunity 🙂

**Comment by timautin** [comment]
Yep seems to be impossible. I'd like to have more time to spent on this, but I don't, sorry ^^ . I already spent 2 days on that popup, that's 2 days lost on something that should be handled by the SDK...
