### ISSUE TITLE
Change the AlertAction background

### ISSUE THREAD

**Issue by samkhawse** [sberrevoets/SDCAlertView#186]
Hi,

Can we customize the AlertAction buttons, like change the background color of the button, etc?

**Comment by sberrevoets** [comment]
Yes, you can set the `backgroundColor` on the instance of your `AlertController`'s `visualStyle` property.

**Comment by samkhawse** [comment]
Hey @sberrevoets, thanks for the quick reply. I really appreciate it. 

If I change the `backgroundColor` property on the  `AlertController` instance, will it change the background color of the entire AlertController. I just want to change the `backgroundColor` of UIButton. Is it possible (_only Ok Button, not the whole AlertController_)?

**Comment by sberrevoets** [comment]
Oh my bad, I missed the "action" part. No, that's not possible at the moment, but I'm not opposed to that functionality. Feel free to submit a PR if you'd like to see that!
