### ISSUE TITLE
Bug in sheet style!

### ISSUE THREAD

**Issue by muei** [sberrevoets/SDCAlertView#190]
My project config:  
` pod 'SDCAlertView', '~> 7.0'`
Xcode: Version 8.0 (8A218a)
SDK: iOS 10.0
iOS deployment iOS 9.3

1.  No action add in `actionSheet` style
```
let alert = AlertController(title: "Title", message: "This is a message", preferredStyle: .actionSheet)
alert.present()
```
so actions is empty, bug in bottom:
```
    private func assignCancelAction() {
        if let cancelActionIndex = self.actions.index(where: { $0.style == .preferred }) {
            self.cancelAction = self.actions[cancelActionIndex]
            self.actions.remove(at: cancelActionIndex)
        } else {
            self.cancelAction = self.actions.first
            self.actions.removeFirst()
        }
    }
```
2. Will be one more action that added in `actionSheet` style
```
let alert = AlertController(title: "Title", message: "This is a message", preferredStyle: .actionSheet)
alert.add(AlertAction(title: "Cancel", style: .preferred))
alert.present()
```
the result will like https://github.com/sberrevoets/SDCAlertView/pull/176, the first image!
3. UIPickerView can't scroll in `actionSheet` style, but worked well in `alert` style

**Comment by sberrevoets** [comment]
I think 1 and 2 are fixed as of 7.1. Can you please check again to make sure this solves your issue as well?

Without the code for the problems you have with UIPickerView it's hard to determine what's wrong, but you may need a different combination of constraints since the layout for an action sheet and an alert are quit different.

**Comment by ohohco** [comment]
```

        let pickerView = UIPickerView()
        alert.contentView.addSubview(pickerView)
        
        pickerView.translatesAutoresizingMaskIntoConstraints = false
        pickerView.heightAnchor.constraint(equalToConstant: 100).isActive = true
        pickerView.centerXAnchor.constraint(equalTo: alert.contentView.centerXAnchor).isActive = true
        pickerView.topAnchor.constraint(equalTo: alert.contentView.topAnchor).isActive = true
        pickerView.bottomAnchor.constraint(equalTo: alert.contentView.bottomAnchor).isActive = true

        // pickerView.backgroundColor = UIColor(white: 0, alpha: 0.5)
         pickerView.showsSelectionIndicator = true

        pickerView.dataSource = self
        pickerView.delegate = self

```

**Comment by sberrevoets** [comment]
That looks fine to me. Are you saying you can't select items in the picker view?

**Comment by ohohco** [comment]
Yeah, when I `actionSheet` style, I can't scroll and select item

**Comment by sberrevoets** [comment]
The solution here is to set `isUserInteractionEnabled = true`. I'm a little reluctant to do this project wide since that would probably break a bunch of projects, but if this is still a problem it's pretty trivial to solve.

Thanks for reporting!
