### ISSUE TITLE
retain cycle prone when presenting SDCAlert on topViewController

### ISSUE THREAD

**Issue by xohozu** [sberrevoets/SDCAlertView#192]
I figured out that SDCAlertView use the `topViewController` of keyWindow if not provide preferred presented view controller. However, UIKit built-in alert does presenting on another window.

If the handler of alert action captures `self`, the topViewController, and not weakify it, a retain cycle prone to be produced.

```objective-c
- (void)showAlert {
    SDCAlertController *alert = [[SDCAlertController alloc] initWithTitle:@"title" message:@"msg"];
    [alert add:[[SDCAlertAction alloc] initWithTitle:@"title" type:EPAlertActionTypeNormal handler:^(SDCAlertAction * _Nonnull action) {
        // do something with `self`
        [self doSomething];  // retain self, and memory leak prone
    }]];
    [alert presentAnimated:YES completion:nil];
}
```

Due to `self` retained presenting alert and alert retained `self` in handler block, a retain cycle occurs. However, the usage in built-in `UIAlertView` will not perform this behavior. 

If I missing something, please note it.

**Comment by xohozu** [comment]
Sorry for my misunderstanding. The SDC presenting behavor is right which is same with UIAlertViewController. So find the topViewController to be presented is correct manner. 

However, there exists memeory leak when showing alert, except action sheet. If I fixed it, I will make a PR.

**Comment by sberrevoets** [comment]
Sounds good, I appreciate your efforts!
