### ISSUE TITLE
UISlider/UIButton inside custom view

### ISSUE THREAD

**Issue by asimonv** [sberrevoets/SDCAlertView#193]
It seems that buttons, sliders, etc cannot be touched when I add a custom to to contentView :-/
Is there a way to fix this?

**Comment by sberrevoets** [comment]
Could this be related to https://github.com/sberrevoets/SDCAlertView/issues/140?

**Comment by asimonv** [comment]
It seems to! Which ```UIScrollView``` should I check?

**Comment by sberrevoets** [comment]
The one that gets instantiated [here](https://github.com/sberrevoets/SDCAlertView/blob/master/Source/Views/AlertView.swift#L19) is a good starting point I think.

**Comment by sberrevoets** [comment]
Going to assume this is a duplicate of the previously mentioned issue so I'm closing this one. If it turns out to be a different problem, feel free to reopen!
