### ISSUE TITLE
An another Question , the alert show too slow

### ISSUE THREAD

**Issue by XHJiang** [sberrevoets/SDCAlertView#196]
When I touch up the alert button,I should stay sometime ,and then zhe alert present.

**Comment by XHJiang** [comment]
touch 
![qq20161223-105205](https://cloud.githubusercontent.com/assets/13825718/21446182/c4ab22e6-c8fd-11e6-880a-a0e07a488923.png)

After three seconds

the alert present
![qq20161223-105303](https://cloud.githubusercontent.com/assets/13825718/21446188/e2a5425e-c8fd-11e6-846c-3e9d1aa1efbd.png)

**Comment by sberrevoets** [comment]
Can you show some code?

**Comment by XHJiang** [comment]
let alertTitleStr : NSMutableAttributedString = NSMutableAttributedString(string: alertTitle)
                alertTitleStr.addAttribute(NSForegroundColorAttributeName, value: UIColor(hex: 0x3E84E0FF), range: NSRange(location: 0 , length: alertTitleStr.length))
                if alertTitle == UserDefaults.standard.object(forKey: FontSet) as! String {
                    alertTitleStr.addAttribute(NSFontAttributeName, value: UIFont(name: "Al-Jazeera-Arabic-Bold", size: 20) ?? UIFont.systemFont(ofSize: 20), range: NSRange(location: 0 , length: alertTitleStr.length))
                } else {
                    alertTitleStr.addAttribute(NSFontAttributeName, value: UIFont(name: "Al-Jazeera-Arabic", size: 20) ?? UIFont.systemFont(ofSize: 20), range: NSRange(location: 0 , length: alertTitleStr.length))
                }
                
                
                let alertAc = AlertAction(attributedTitle: alertTitleStr, style: .normal, handler: { (alertAc) in
                    UserDefaults.standard.set(alertTitle, forKey: FontSet)
                    UserDefaults.standard.synchronize()
                })
                
                alert.add(alertAc)
}

**Comment by XHJiang** [comment]
Very simple code,I print the event when I touch.the alert con not work ,I should touch another ,and then it alert

**Comment by XHJiang** [comment]
For the first time I click trigger bounced,But bounced didn't appear,I need to click anywhere on the screen,It work

**Comment by XHJiang** [comment]
HELLO~~
