### ISSUE TITLE
Can't use on Obj-c

### ISSUE THREAD

**Issue by capezzbr** [sberrevoets/SDCAlertView#199]
I've followed the install guide:

```
platform :ios, '8.0'
use_frameworks!

target 'MyApp' do
  pod 'SDCAlertView', '~> 7.1'
end
```

and then

```
pod install
```

It installed the pod properly, but I can't seem to find a way to import the library to my Objective-c code. When typing `#import <` or `#import "` Xcode doesn't suggest me anything similar to `SDCAlertView`. Any advice?

**Comment by sberrevoets** [comment]
Hmm, that's strange. Are you opening your .xcworkspace file after doing `pod install`?

**Comment by capezzbr** [comment]
Yes I am, I can't actually use it even on my Swift files:

![image](https://cloud.githubusercontent.com/assets/3534630/22021469/5ac301ca-dc9c-11e6-9985-94e731682e6d.png)

it might be it depends by the version of Swift the library is using? The Swift version used in my project is `2.3`, any advice?

**Comment by capezzbr** [comment]
Ok, using the version `6.0` of the library solves the issue as it is based on Swift 2.3. One last question for you before we consider the issue closed, there are any plans to keep updating the lib using Swift 2.3 or I should seriously consider to migrate my app to Swift 3?

**Comment by capezzbr** [comment]
Also, now that I am thinking about it better, do you have any reason as why I am unable to use the library in Objc?

**Comment by sberrevoets** [comment]
You should definitely consider upgrading to Swift 3.0, as Xcode 8.3 will not support Swift 2.3 anymore. Swift 3 (and soon 3.1, 4, etc.) is the future.

There should be no reason you can't use the project in Objective-C. What problem do you see when trying to use it from Objective-C?

**Comment by capezzbr** [comment]
> You should definitely consider upgrading to Swift 3.0

Yep, agree, thanks 👍 

> There should be no reason you can't use the project in Objective-C.

So I managed to let the library work on both Swift and Obj-c by using version `6.0`. 

Going to close this as that was something on my side rather than on the library. Thanks for helping out

**Comment by sberrevoets** [comment]
The current version should also work in Objective-C though. If it doesn't there's still a problem somewhere.
