### ISSUE TITLE
assignResponder bug

### ISSUE THREAD

**Issue by rladudrl602** [sberrevoets/SDCAlertView#200]
TextFields doesn't become the first responder due to a bug in AlertController.swift

In AlertController.swift line 224, 

_ = self.assignResponder is not calling the closure.

need to add () to actually focus the first textField.

**Comment by sberrevoets** [comment]
Thanks for reporting this. Are you interested in submitting a PR for this?

**Comment by rladudrl602** [comment]
I'm not sure if it deserves one. All that I'll do Is change
`_ = self.assignResponder` 
to
` _ = self.assignResponder()` 
in AlertController.swift line 224.

**Comment by sberrevoets** [comment]
Thanks for bringing this up, should be fixed in version 7.1.1.
