### ISSUE TITLE
preferredAction doesn't support Enter key

### ISSUE THREAD

**Issue by futuretap** [sberrevoets/SDCAlertView#201]
When assigning an alert including a textField the `preferredAction` property, the alert is not closed when hitting the Enter key. I have specified

    textField.returnKeyType = UIReturnKeyDone;

This is in contrast to Apple's documentation for the `UIAlertController.preferredAction` property.

For almost all alerts with a textField it would be desirable to let the user accept the dialog by tapping the Return key on the keyboard.

**Comment by sberrevoets** [comment]
Nice catch, this is definitely an oversight. Would you be interested in fixing this? I don't have too much (read: any) experience with external keyboard handling so not sure when I'll be able to get to this.

**Comment by futuretap** [comment]
Probably it would be sufficient to just implement `UITextFieldDelegate.textFieldShouldReturn()`. Not sure if I can implement it anytime soon - more so since I'd have to familiarize myself with your code first.

Also, I might be able to get away with the system UIAlertController - we'll see.

**Comment by sberrevoets** [comment]
Sounds good, thanks for bringing this up regardless!

**Comment by sberrevoets** [comment]
This is fixed in https://github.com/sberrevoets/SDCAlertView/pull/255
