### ISSUE TITLE
Using UITextView as contentView's subview

### ISSUE THREAD

**Issue by jVirus** [sberrevoets/SDCAlertView#203]
Can someone help me figure out how to add `UITextView` as a subview of `contentView`? As far as I know it should not be hard to accomplish, but I miss something. 

As a result, the code displays a blank `AlertView` without even buttons (`Cancel`, `Save`). I would appreciate any help.

        let alert = AlertController(title: nil, message: nil, preferredStyle: .alert)

        let textView = UITextView()
        textView.backgroundColor = UIColor.clear
        textView.font = UIFont(name: "Helvetica", size: 15.0)
                
        alert.contentView.addSubview(textView)
        
        textView.topAnchor.constraint(equalTo: alert.contentView.topAnchor).isActive = true
        textView.bottomAnchor.constraint(equalTo: alert.contentView.bottomAnchor).isActive = true
        textView.leftAnchor.constraint(equalTo: alert.contentView.leftAnchor).isActive = true
        textView.rightAnchor.constraint(equalTo: alert.contentView.rightAnchor).isActive = true
        
        
        alert.add(AlertAction(title: "Cancel", style: .normal))
        alert.add(AlertAction(title: "Save", style: .preferred))
        alert.present()

**Comment by sberrevoets** [comment]
Since a `UITextView` is a scroll view, my guess is that you also have to specify the dimensions of the text view, so in addition to the constraints you created you'll have to give it a height and width constraint as well.

**Comment by jVirus** [comment]
Hmm, you are right. However, after specifying `frame` for `UITextView` it didn't give any different results:

        let margin:CGFloat = 8.0
        let rect = CGRect(x: margin, y: margin, width: alert.view.bounds.size.width - margin * 2.0, height: 40.0)
       
        let textView = UITextView(frame: rect)

**Comment by sberrevoets** [comment]
Auto Layout will overrule the frame you give it. You'll need to give it a height and width using constraints.

**Comment by jVirus** [comment]
@sberrevoets Thank you very much man!
