### ISSUE TITLE
Extra Space above ContentView

### ISSUE THREAD

**Issue by jrl290** [sberrevoets/SDCAlertView#207]
My custom UIView has extra space above it that I'd like to get rid of. I am using an older version of SDCAlertView because I'm not quite ready to switch to Swift 3. Is this an obvious issue that perhaps I'm not understanding properly? 

I can put negative constants on the top and bottom anchors but that causes the AM/PM button to lose some of its touch box.

```
       container.centerXAnchor.constraintEqualToAnchor(alert.contentView.centerXAnchor).active = true
        container.topAnchor.constraintEqualToAnchor(alert.contentView.topAnchor).active = true
        container.bottomAnchor.constraintEqualToAnchor(alert.contentView.bottomAnchor).active = true
        
        container.leftAnchor.constraintEqualToAnchor(alert.contentView.leftAnchor).active = true
        container.rightAnchor.constraintEqualToAnchor(alert.contentView.rightAnchor).active = true
```

![simulator screen shot feb 20 2017 2 51 42 pm](https://cloud.githubusercontent.com/assets/1811031/23139801/4736bf7a-f77c-11e6-9852-51931c4db6f6.png)

**Comment by sberrevoets** [comment]
Take a look at https://github.com/sberrevoets/SDCAlertView/blob/master/Source/AlertVisualStyle.swift. You'll want to modify the `verticalElementSpacing`, though I think if you set that to 0, it may also remove the spacing between the title and message labels.

**Comment by jrl290** [comment]
Works for me! All I needed was a trim. Thank you
