### ISSUE TITLE
Release cycle when adding actions referencing self

### ISSUE THREAD

**Issue by twiedow** [sberrevoets/SDCAlertView#208]
I'm seeing problems with release cycles when using SDCAlertView. 

The following code (SDCAlertView or UIKit) is called within a method when pressing a button. Within the action method another method of self is called where a simple print statement is called.
I don't capture self as weak or unowned since the alert controller is only referenced in the method locally and not stored in a member variable of the view controller.

The weird thing is that using SDCAlertView the view controller is never deinit'ed, but when using UIKit deinit is called.
The workaround is to use [unowned self] in the block, but maybe you have an idea why the behaviour is different to UIKit.

SDCAlertView

```
    let alert = AlertController(title: "Test", message: "Test")
    alert.add(AlertAction(title: "OK", style: .normal, handler: { (action) in
      self.printsome()
    }))
    alert.present()
```

UIKit

```
    let alert = UIAlertController(title: "Test", message: "Test", preferredStyle: .alert)
    alert.addAction(UIAlertAction(title: "OK", style: .default, handler: { (action) -> Void in
      self.printsome()
    }))
    present(alert, animated: true, completion: nil)
```

**Comment by sberrevoets** [comment]
Good find! This is likely due to an implementation detail in SDCAlertView that inadvertently creates a retain cycle. Haven't confirmed this myself, but a retain cycle like that definitely shouldn't be happening.

**Comment by twiedow** [comment]
Ok, good to know. Do you already where the problem is located or how to fix it? Or maybe you already have a bugfix ... :-) Please let me know, otherwise I will have to add the capture statement everywhere I add an action like this...

**Comment by sberrevoets** [comment]
Sorry, this is the first time I hear about it so I have no idea where to look for this yet 😕

**Comment by twiedow** [comment]
Got it. Btw, the Debug Memory Graph in Xcode 8 is great! There is a release cycle in AlertController in the assignResponder block. I will post a PR.

**Comment by twiedow** [comment]
PR is posted. Can you please check it? Can you make a new release once this is checked?

**Comment by sberrevoets** [comment]
Let's continue this [here](https://github.com/sberrevoets/SDCAlertView/pull/209).
