### ISSUE TITLE
UICollectionView in contentView does not scroll

### ISSUE THREAD

**Issue by antipex** [sberrevoets/SDCAlertView#210]
I'm adding a `UICollectionViewController` with a horizontal `UICollectionViewFlowLayout` to the `contentView` of an action sheet, and although it appears normally, it doesn't scroll. If I add the same collection view to a generic `UIViewController` it works fine.

Here's how I'm setting it up:

```
CameraRollController *cameraRoll = [[CameraRollController alloc] initWithCollectionViewLayout:layout];

[alertController addChildViewController:cameraRoll];

[alertController.contentView addSubview:cameraRoll.view];

[cameraRoll.view autoSetDimension:ALDimensionHeight toSize:preferredCellSize.height];
[cameraRoll.view autoPinEdgesToSuperviewEdges];

[cameraRoll didMoveToParentViewController:alertController];

[alertController presentAnimated:YES completion:nil];
```

Am I missing something here?

**Comment by sberrevoets** [comment]
Not entirely sure what's happening here, but I suspect the collection view's scroll view and the action sheet's scroll view are in conflict. If you can upload a sample project somewhere that reproduces this I might be able to take a look.

**Comment by antipex** [comment]
Awesome, thanks!

Here's a repo containing a sample project which reproduces the issue:

https://github.com/antipex/collection-view-scrolling

**Comment by antipex** [comment]
FYI – I was able to work around this by setting `userInteractionEnabled` to `YES` on `contentView`.

**Comment by sberrevoets** [comment]
Interesting, can you try this with https://github.com/sberrevoets/SDCAlertView/tree/fix-delay and see if that fixes the problem?

**Comment by antipex** [comment]
The issue still occurs with the `fix-delay` branch.

**Comment by sberrevoets** [comment]
Hmm, ok. Thanks for verifying. I think setting `userInteractionEnabled` is a reasonable solution. Not sure I'd want to change that internally since others may be relying on the behavior of the content view not being intractable.

**Comment by antipex** [comment]
Okay, thanks for the help!
