### ISSUE TITLE
Why don't change the status of the cancel button on the main branch

### ISSUE THREAD

**Issue by XHJiang** [sberrevoets/SDCAlertView#211]

**Comment by sberrevoets** [comment]
I'm guessing this is in reference to https://github.com/sberrevoets/SDCAlertView/issues/195? I was waiting for you to confirm that the branch in posted in there actually solved the problem.

**Comment by XHJiang** [comment]
yes, nice

**Comment by sberrevoets** [comment]
I just released 7.1.2 which has a fix for the problem you're experiencing.
