### ISSUE TITLE
Crash when displaying alert

### ISSUE THREAD

**Issue by jtjacka** [sberrevoets/SDCAlertView#212]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/CA61B9DB-07E3-4BC7-8E22-36983B7997E9/*****.app> (loaded)' with name 'ActionCell''

Getting this crash all of a sudden with the latest version of SDCAlertView, it happens when the alert is presented.

**Comment by jtjacka** [comment]
> presented

**Comment by sberrevoets** [comment]
Hmm, weird. Which version were you using before? Did you recently upgrade to Xcode 8.3?

**Comment by jtjacka** [comment]
@sberrevoets I did just upgrade to Xcode 8.3 so that could be the cause, looks like I upgraded to 7.1.2 before I upgraded to Xcode 8.3

**Comment by sberrevoets** [comment]
We actually saw this same crash in our app (that doesn't even use SDCAlertView) with an unrelated XIB for a long time, but at some point it just... disappeared. I think this is a system level issue, but we never were able to reproduce so I'm unsure what to do about it unfortunately 😕

**Comment by jtjacka** [comment]
That is not ideal. :(  but I'll see what I can do about it, maybe I'll try building on another device and/or machine.

**Comment by sberrevoets** [comment]
It would also be good to isolate the 2 changes (Xcode 8.3 and 7.1.2 of SDCAlertView) to see which change caused this crash. I find it highly unlikely that the 1 change that was part of 7.1.2 causes this crash.

**Comment by jtjacka** [comment]
@sberrevoets switched back to a different branch of my project and it works fine again.... no idea why, but whatever.  Going to close the issue.

**Comment by jtjacka** [comment]
@sberrevoets if you're curious I figured out what the issue is, I added a new cocoapod recently called 'Apptimize' and they seem to interfere with each other somehow.
