### ISSUE TITLE
Xcode 8.3 reports not Swift 3 (CacoaPods)

### ISSUE THREAD

**Issue by gregucsd** [sberrevoets/SDCAlertView#213]
After updating to 7.1.2 using CocoaPods Xcode reports that SDCAlertView needs to be converted to Swift 3.  
![convert](https://cloud.githubusercontent.com/assets/7065988/25112998/9f1751d8-23a9-11e7-9214-9709d2c8b010.png)

**Comment by sberrevoets** [comment]
Do you have a sample project I can look at by any chance? What version of CocoaPods are you using?

**Comment by gregucsd** [comment]
Apologies.  Pod was out of date.
