### ISSUE TITLE
Swift 4 or iOS 11 prevents keyboard dismissing

### ISSUE THREAD

**Issue by Spark3000** [sberrevoets/SDCAlertView#217]
It might be me, but I can't get the keyboard to dismiss when compiled for iOS 11.

**Comment by Spark3000** [comment]
?

**Comment by sberrevoets** [comment]
I just pushed a `swift-4` branch that I worked on last week, can you try it with that. I saw some differences in the keyboard dismissing behavior, but that that it wouldn't dismiss at all.

If you're still seeing it on that branch, can you please add some detail to this issue?

**Comment by Spark3000** [comment]
AWESOME. Will try and let you know. THANKS

**Comment by Spark3000** [comment]
Branch `swift-4` seems to be working 👍🏻️

**Comment by sberrevoets** [comment]
Great!
