### ISSUE TITLE
iOS device compatibility on branch 'Swift-4'

### ISSUE THREAD

**Issue by Spark3000** [sberrevoets/SDCAlertView#218]
Mainly with Layout Anchors. Getting loads of warnings from compiler about iOS 9+ compatibility. Bypassing them with @ availability condition at the moment.

**Comment by Spark3000** [comment]
Sorry (NOOB)
Just changing deployment targets for now.

**Comment by sberrevoets** [comment]
Yeah I plan on upgrading the minimum deployment target to iOS 8 with a new major version in the fall, so those warnings are expected.
