### ISSUE TITLE
No notifications on outside tap

### ISSUE THREAD

**Issue by jdrevet** [sberrevoets/SDCAlertView#219]
When the `DismissOnOutsideTap` behavior is set, there is no way to be notified when the alert is dismissed. 
I can do a PR (perhaps with an `outsideTapHandler` ?) if you think that it could fit some needs.

**Comment by sberrevoets** [comment]
Yeah I think an `outsideTapHandler` would work for that purpose. Would be great if you had some time to submit a PR!
