### ISSUE TITLE
Have accessibilityIdentifiers on alert buttons for test automation

### ISSUE THREAD

**Issue by tdesert** [sberrevoets/SDCAlertView#223]
Hello!
I'd like to be able to have UI automation tests on SDCAlertView using `accessibilityIdentifier`.
Do you have any insight on how this could be done with the current state of the lib?
Many thanks!

**Comment by sberrevoets** [comment]
Not anything in particular, but adding `accessibilityIdentifier`s to the different alert elements seems like a good improvement. I think this wouldn't be too difficult to do either, so feel free to take a stab at it!

**Comment by tdesert** [comment]
Thanks! I'll give it a try

**Comment by sberrevoets** [comment]
Let's continue this in #225
