### ISSUE TITLE
Swift 4 branch has iOS deployment target set to iOS 9

### ISSUE THREAD

**Issue by mostafaberg** [sberrevoets/SDCAlertView#231]
I've been taking a look at the Swift 4 branch and it seems like the deployment target has been raised to 9.0, is there a reason behind that ? i see that there are OS version checks against iOS 9 in the code, which means that things should still work on iOS 8 , any thoughts?

**Comment by sberrevoets** [comment]
The intention was to increase the deployment target to iOS 9 (so that layout anchors become available), which would alleviate the need for any availability checks for that version. If you can point me to where there still are checks for iOS 9 I'll be sure to remove those.

**Comment by mostafaberg** [comment]
Aha, that's why, now it makes sense :)

Here are all the references for iOS checks I found:
https://github.com/sberrevoets/SDCAlertView/blob/7be4e2f344c9f6632d6dd061d3ad6783cc4f9889/Source/AlertBehaviors.swift#L22
https://github.com/sberrevoets/SDCAlertView/blob/091a853fd137e1800aefefdbda746f3f2ae17578/Example/TestsViewController.swift#L3
https://github.com/sberrevoets/SDCAlertView/blob/7be4e2f344c9f6632d6dd061d3ad6783cc4f9889/Example/DemoViewController.swift#L49
https://github.com/sberrevoets/SDCAlertView/blob/0bdb3d9dbe00e06a481b119c8160d52f00be9425/Source/AlertVisualStyle.swift#L84
https://github.com/sberrevoets/SDCAlertView/blob/660858149b1177e7fc7f7af4f7cbddf74d743278/Source/AlertController.swift#L76

I'm closing this issue now as it answered my question 👍

**Comment by sberrevoets** [comment]
Hah wow, I guess I hadn't done that pass yet. Thanks for flagging! I'll remove this before merging that branch into master.

**Comment by mostafaberg** [comment]
Oh no wait, my bad, i actually hit master branch when searching, i thought i could search within the current branch :), seems like you actually did have that sorted out already so you may ignore my links :D
