### ISSUE TITLE
adding subview to alert makes it invisible

### ISSUE THREAD

**Issue by ua24** [sberrevoets/SDCAlertView#239]
even if I try code from readme it does not work
```swift
let spinner = UIActivityIndicatorView(activityIndicatorStyle: .gray)
spinner.translatesAutoresizingMaskIntoConstraints = false
spinner.startAnimating()

let alert = AlertController(title: "Title", message: "Please wait...")
alert.contentView.addSubview(spinner)

spinner.centerXAnchor.constraint(equalTo: alert.contentView.centerXAnchor).isActive = true
spinner.topAnchor.constraint(equalTo: alert.contentView.topAnchor).isActive = true
spinner.bottomAnchor.constraint(equalTo: alert.contentView.bottomAnchor).isActive = true

alert.present()
```

will not show any alert just dimm the screen until you tap somewhere
I'm using - SDCAlertView (8.0) - from Podfile.lock

**Comment by jonaszmclaren** [comment]
Any solution to this?

**Comment by sberrevoets** [comment]
Can you submit a sample project that shows this behavior? I just copy/pasted the code you posted into the demo project and it works as expected.

**Comment by ua24** [comment]
I'm sorry just test on clean project just with pod 'SDCAlertView' and it works, probably one of my pods conflict with SDCAlertView pod.
My Podfile looks like this
`# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Crypt test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Crypt test
pod 'AFNetworking'
pod 'Alamofire'
pod 'Parse'
pod 'ParseUI'
pod 'Bolts'
pod 'GoogleMaps'
pod 'SinchVerification'
pod 'OneSignal'
pod 'ParseFacebookUtilsV4'
pod 'FBSDKShareKit'
pod 'Fabric'
pod 'Crashlytics'
pod 'WootricSDK'
pod 'SDCAlertView'
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'SDWebImage'
pod 'Socket.IO-Client-Swift'
pod 'WebRTC'
pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"
pod 'BAFluidView'
#pod 'MXParallaxHeader'
#pod 'YandexMobileMetrica/Dynamic', '2.9.1''
end
`
