### ISSUE TITLE
Xcode 9, swift 4, many syntax error while compiling

### ISSUE THREAD

**Issue by dekelm8** [sberrevoets/SDCAlertView#240]
There's a lot syntax error i can't compile my project 
using pod 'SDCAlertView'
is there something i'm missing here?

**Comment by sberrevoets** [comment]
The latest version has a number of breaking changes, so you'll have to resolve those first.

**Comment by dekelm8** [comment]
> so you'll have to resolve those first.

solve what exactly?
/

**Comment by sberrevoets** [comment]
Make changes from the 7.x syntax to the 8.x syntax.

**Comment by SchmidtyApps** [comment]
@dekelm8 I had the same issue it was because my Pod repo was out of date so it was installing version 7 of this repo instead of version 8. Call `pod repo update` via command line before running `pod install`

**Comment by sberrevoets** [comment]
I'll assume that was the problem, so closing this.
