### ISSUE TITLE
AlertView doesn't support dynamic type

### ISSUE THREAD

**Issue by cortis** [sberrevoets/SDCAlertView#244]
Unlike Apple's alertview, SDCAlertView doesn't change in size when the user changes the size of type in Settings.

**Comment by sberrevoets** [comment]
Ah, that's a good call. Definitely worth doing.

**Comment by cortis** [comment]
BTW: It's a great framework.  Thanks!

**Comment by sberrevoets** [comment]
Awesome, glad it's useful!

**Comment by sberrevoets** [comment]
Let's continue the conversation in https://github.com/sberrevoets/SDCAlertView/pull/246
