### ISSUE TITLE
Using attributedTitle and attributedMessage to workaround lack of support for dynamic type has layout issues

### ISSUE THREAD

**Issue by cortis** [sberrevoets/SDCAlertView#245]
You can workaround the fact that SDCAlertView doesn't support dynamic type by using UIFont.prefferredFont(forTextStyle: .headline) and .subheadline.  This works reasonably well, but has some layout issues.  For very large type the title and message text will overlap.  For very small type there is too much vertical padding.

**Comment by sberrevoets** [comment]
I assume the same happens when taking the font value for a given dynamic type and using that directly? In that case, it sounds like the constraints are not well defined.

**Comment by cortis** [comment]
I haven't tried that.  I do have a fix for this one, I'm prepping it for a pull request right now.

**Comment by sberrevoets** [comment]
Let's continue this conversation in https://github.com/sberrevoets/SDCAlertView/pull/246
