### ISSUE TITLE
Switch off "dismiss on outside tap" behavior

### ISSUE THREAD

**Issue by ckalbas** [sberrevoets/SDCAlertView#249]
I have an alert which I don't want users to dismiss on tapping outside.

I read this behavior is enabled for action sheets by default, but I'm getting it also with alert.

How do I turn this behavior off?

**Comment by sberrevoets** [comment]
There was a bug with this that got fixed here: https://github.com/sberrevoets/SDCAlertView/pull/242.

I have yet to create a release with that update included (sorry, coming soon!), but if you use master in the meantime this should be fixed.

**Comment by ckalbas** [comment]
Thanks!
