### ISSUE TITLE
Action sheet interactable UI components don't work

### ISSUE THREAD

**Issue by SchmidtyApps** [sberrevoets/SDCAlertView#254]
When adding a UI item like a switch, button, textfield etc to the custom content view on an action sheet the user can not click on those items. You can see this in the example app with the "switch" content type. Clicking on it does nothing.

**Comment by SchmidtyApps** [comment]
Looks like the culprit is in ActionSheetView.xib the content view "User Interaction Enabled" checkbox is not selected.

**Comment by sberrevoets** [comment]
If the issue is that `contentView.isUserInteractionEnabled = false`, then that's more or less expected (see https://github.com/sberrevoets/SDCAlertView/issues/224). Opting everybody into an interactable contentView is probably not ideal if it wasn't like that from the beginning.

**Comment by cprovatas** [comment]
@sberrevoets Why would enabling user interaction on the content view not be ideal?  Seems like an annoying extra step to enable controls if it doesn't break anything to begin with.

**Comment by sberrevoets** [comment]
> if it doesn't break anything to begin with

That's a big if right there :) Since I don't know how people use this, I can't say whether this would break for anyone or not.
