### ISSUE TITLE
 Install SDCAlertView using cocoapods has a bug

### ISSUE THREAD

**Issue by fengerxixi** [sberrevoets/SDCAlertView#257]
Hi
 if  i use cocopods to install that will make alertview disappear by touchup outside

my xcode version is 9.2 and ios 11.2.1

**Comment by sberrevoets** [comment]
I think that's fixed with https://github.com/sberrevoets/SDCAlertView/pull/242

**Comment by sberrevoets** [comment]
Gonna close this, feel free to reopen if you still have this problem!
