### ISSUE TITLE
Bug with Fastlane

### ISSUE THREAD

**Issue by Den-Ree** [sberrevoets/SDCAlertView#258]
Hello, thank you for your lib.
When I tried to use it with Fastlane build and I have error:

`error: unexpected duplicate task: CompileXIB /Users/contentoffice/builds/985c6c00/0/product/ios/app/Pods/SDCAlertView/Source/Views/ActionSheetView.xib (in target 'SDCAlertView')`

I have investigated and found this [solution](https://github.com/CocoaPods/CocoaPods/issues/7079). 

Could you suggest something?

**Comment by sberrevoets** [comment]
Thanks for reporting this, I think this will be addressed in https://github.com/sberrevoets/SDCAlertView/pull/260
