### ISSUE TITLE
UIActionSheet content view missing

### ISSUE THREAD

**Issue by ReDetection** [sberrevoets/SDCAlertView#261]
I mean there is no contentView anymore on the view hierarchy. Also disappeared from the example, look: left is 7.1.2, same for 8.0.1, right is 8.0.2:

![simulator screen shot - iphone 5s - 2018-02-02 at 15 05 39](https://user-images.githubusercontent.com/458005/35722927-edf08110-082a-11e8-8b6d-aab580471067.png) ![simulator screen shot - iphone 5s - 2018-02-02 at 15 06 35](https://user-images.githubusercontent.com/458005/35722928-f08fd65a-082a-11e8-82a9-2642d1464261.png)

**Comment by sberrevoets** [comment]
Let's continue in #262
