### ISSUE TITLE
Setting tintColor on the alert.view affects contentView

### ISSUE THREAD

**Issue by avolovoy** [sberrevoets/SDCAlertView#263]
There is a weird behavior in regards to setting tintColor on alert.view. It being set before contentView is configured - contentView doesn't show up at all. 
To reproduce - in Example app - add   alert.view.tintColor = .red before line 55 of DemoViewController spinner doesn't show. If this line added after contentView adding spinner - everything is fine.

**Comment by sberrevoets** [comment]
Yeah this is not surprising because when the view is loaded the entire alert is being built up and mostly immutable at that point. I recommend not accessing the view until after the alert is fully configured.

**Comment by avolovoy** [comment]
Ok.. make sense.
