### ISSUE TITLE
Long message causes UI overlaps

### ISSUE THREAD

**Issue by Baaroon** [sberrevoets/SDCAlertView#275]
Hi :)
When using actionSheet mode with long text messages, the message part overlaps with action buttons. 

![simulator screen shot - iphone x - 2018-07-30 at 19 07 50](https://user-images.githubusercontent.com/12879963/43404748-7b7114bc-942d-11e8-8d55-dea5a65a121e.png)

**Comment by sberrevoets** [comment]
Yikes, thanks for the report!

**Comment by Baaroon** [comment]
I fixed it and sent a pull request :)

**Comment by sberrevoets** [comment]
Thank you, let's continue there!
