### ISSUE TITLE
Show actionSheet without title or message

### ISSUE THREAD

**Issue by langyanduan** [sberrevoets/SDCAlertView#278]
```
SDCAlertController *alert = [[SDCAlertController alloc] initWithTitle:@"title" 
                                                              message:nil
                                                       preferredStyle:SDCAlertControllerStyleActionSheet];
```

if create alertController like this, it will leave a lot of space

**Comment by sberrevoets** [comment]
That sounds similar to https://github.com/sberrevoets/SDCAlertView/pull/251, is that not fixed in the latest version?

**Comment by langyanduan** [comment]
```
PODS:
  - SDCAlertView (8.1)
```

![simulator screen shot - iphone x - 2018-08-29 at 09 34 49](https://user-images.githubusercontent.com/2404894/44759953-38f37900-ab6f-11e8-90bd-94ee45c4e368.png)

**Comment by langyanduan** [comment]
I think it should look like UIAlertController

![simulator screen shot - iphone x - 2018-08-29 at 09 40 01](https://user-images.githubusercontent.com/2404894/44760061-bae3a200-ab6f-11e8-910c-39603b336e44.png)

**Comment by sberrevoets** [comment]
Thanks for reporting. Just pushed 
https://github.com/sberrevoets/SDCAlertView/commit/c4f2d71249d94e211050fb977753a7cb77ecd00f that should fix this.
