### ISSUE TITLE
Customize separator line above the buttons on the alert

### ISSUE THREAD

**Issue by DamascenoRafael** [sberrevoets/SDCAlertView#279]
I'm still using version 2.5.4 of SDCAlertView. I recently tried to upgrade to the latest version and also to the Swift code, but I'm wondering if it's still possible to customize the separator line above the buttons on the alert.

In the current code (available at https://github.com/caronae/caronae-ios/blob/master/Caronae/Extras/CaronaeAlertController.m):

```
UIImageView *separatorView = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"SeparatorColor"]];
[self.contentView addSubview:separatorView];
```

![image](https://user-images.githubusercontent.com/9842644/44952636-a8f94c00-ae5a-11e8-92aa-7ffaef2c5251.png)

But I did not get the same result in the current version of the library trying to reproduce the same steps.

Any idea if it is still possible to do this customization or if there is another way to do it?

**Comment by DamascenoRafael** [comment]
With the following code in the latest version of the lib (9.0) I get the result of the image below.
I tried to change the constraints but I could not get the result I had with the older version.

```
let separatorView = UIImageView(image: UIImage(named: "SeparatorColor"))
let alert = AlertController(title: "Title", message: "msg")
alert.addAction(AlertAction(title: "Dismiss", style: .preferred))
alert.contentView.addSubview(separatorView)
alert.present()
```

![simulator screen shot - iphone 8 plus - 2018-09-26 at 22 56 13](https://user-images.githubusercontent.com/9842644/46119220-6a984800-c1e0-11e8-8d27-aa4ec64b4789.png)

**Comment by sberrevoets** [comment]
Sorry, this slipped my attention. I believe you can fix this by setting the alert's `visualStyle.contentPadding` to 0. Note that means you'll have to indent all your other elements manually.

**Comment by DamascenoRafael** [comment]
Thanks for reply @sberrevoets. There seems to be a combination of numbers that I can use to get the separator in the position I'm looking for (not exactly zero).
But then is there a way that how can I access the `titleLabel` and `messageLabel` to change the constraints or any other setting to keep the texts in the same position?

**Comment by sberrevoets** [comment]
Unfortunately not. The only options you have at that point are to either create the labels yourself, or, not as nice but certainly easier, create the constraint of your border with negative constants equal to `visualStyle.contentPadding`.

**Comment by DamascenoRafael** [comment]
Thank you for your help! Unfortunately this really doesn't sound like a very elegant solution. Is this kind of feature still being planned for future releases? I mean, it used to be quite simple to customize the separation line.

**Comment by sberrevoets** [comment]
This behavior isn't really supported out of the box. In the old version it only worked because of implementation details (no padding around the content view), but the visual style doesn't provide for a custom separator image. This seems like enough of an edge case that I don't think this should be part of the library.

In your case I'd probably create an `AlertController` extension that deals with this and you can call from where you need to.
