### ISSUE TITLE
Release date for Swift 4.2 support

### ISSUE THREAD

**Issue by twiedow** [sberrevoets/SDCAlertView#281]
I just saw that you already have a branch with Swift 4.2 support.
I would like to know when do you plan to make a release with those changes?

Thanks for your great work!

**Comment by sberrevoets** [comment]
I'll do my best to get it out this weekend, time is hard to come by nowadays :) Thanks for your patience!

**Comment by sberrevoets** [comment]
I just released 9.0 which is the 4.2 compatibility release
