### ISSUE TITLE
Swift 4.2 Version - Xcode 10

### ISSUE THREAD

**Issue by KarthikSCP** [sberrevoets/SDCAlertView#282]
When I do a _pod install_. My Xcode build settings still points to Swift4.0 compiler.
Please update .swift_version file to point it to Swift 4.2.

**Comment by sberrevoets** [comment]
Thanks for the heads up, I just pushed this change. I don't believe it requires a CocoaPods update, but if it does let me know and I can do that.

**Comment by sberrevoets** [comment]
Closing this, let me know if you still have problems!
