### ISSUE TITLE
How to use AlertBehaviors in Obj-c?

### ISSUE THREAD

**Issue by M-I-N** [sberrevoets/SDCAlertView#289]
When using SDCAlertView in `Swift`, there is an option to control behaviors. Like:

```swift
let alertController: AlertController = . . .

alertController.behaviors = .dismissOnOutsideTap
```

But as I need to use SDCAlertView in `Objective-C` how can I use the `.dismissOnOutsideTap`?
I've tried:

```obj-c
alertController.behaviors = AlertBehaviorsDismissOnOutsideTap;
```
But it seems that the `behaviors` property can't be accessed in Objective-C. 

I think there are compatibility issues when bridging between `Swift`-`Objective-C`. How to resolve this?

**Comment by sberrevoets** [comment]
Sorry, alert behaviors are not available in Objective-C.
