### ISSUE TITLE
Error with Catalyst

### ISSUE THREAD

**Issue by jacobwhite** [sberrevoets/SDCAlertView#297]
I know its still beta but I'm getting this error when I try to build for Mac using Catalyst. Has anyone run across this?

```
ompileXIB /Volumes/Macintosh\ SSD/Users/jacob/Documents/AppName/SDCAlertView/Actions/ActionCell.xib (in target 'app name' from project 'App Name')
    cd /Volumes/Macintosh\ SSD/Users/jacob/Documents/AppName
    export XCODE_DEVELOPER_USR_PATH="/Volumes/Macintosh SSD/Users/jacob/Downloads/Xcode-beta.app/Contents/Developer/usr/bin/.."
    /Volumes/Macintosh\ SSD/Users/jacob/Downloads/Xcode-beta.app/Contents/Developer/usr/bin/ibtool --errors --warnings --notices --platform macosx --target-device ipad --module app_name --output-partial-info-plist /Users/jacob/Library/Developer/Xcode/DerivedData/app_name-ehluajhqegozhgfxsgtzlakkzcbr/Build/Intermediates.noindex/App\ Name.build/Debug-maccatalyst/app\ name.build/ActionCell-PartialInfo.plist --auto-activate-custom-fonts --minimum-deployment-target 13.0 --output-format human-readable-text --compile /Users/jacob/Library/Developer/Xcode/DerivedData/app_name-ehluajhqegozhgfxsgtzlakkzcbr/Build/Products/Debug-maccatalyst/app\ name.app/Contents/Resources/ActionCell.nib /Volumes/Macintosh\ SSD/Users/jacob/Documents/AppName/SDCAlertView/Actions/ActionCell.xib
```
2019-08-09 17:22:42.922 ibtoold[5573:70225] DEBUG: Added to environment: {
    CFStringDisableROM = 1;
}
dyld: Symbol not found: _OBJC_CLASS_$__UICommandIdentifier
  Referenced from: /Volumes/Macintosh SSD/Users/jacob/Downloads/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/iOSSupport/Library/PrivateFrameworks/IBCocoaTouchToolFoundation.framework/IBCocoaTouchToolFoundation (which was built for Mac OS X 13.0)
  Expected in: /System/iOSSupport/System/Library/Frameworks/UIKit.framework/Versions/A/UIKit
 in /Volumes/Macintosh SSD/Users/jacob/Downloads/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/iOSSupport/Library/PrivateFrameworks/IBCocoaTouchToolFoundation.framework/IBCocoaTouchToolFoundation
2019-08-09 17:22:44.688 ibtoold[5573:70225] *** Terminating app due to uncaught exception 'IBPlatformToolFailureException', reason: 'The tool closed the connection

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_FALLBACK_LIBRARY_PATH=
DYLD_FRAMEWORK_PATH=/Volumes/Macintosh SSD/Users/jacob/Downloads/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/iOSSupport/usr/bin:/Volumes/Macintosh SSD/Users/jacob/Downloads/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/iOSSupport/Library/PrivateFrameworks
DYLD_LIBRARY_PATH=

Dyld Error Message:
  Symbol not found: _OBJC_CLASS_$__UICommandIdentifier
  Referenced from: /Volumes/VOLUME/Users/*/Downloads/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/iOSSupport/Library/PrivateFrameworks/IBCocoaTouchToolFoundation.framework/IBCocoaTouchToolFoundation (which was built for Mac OS X 13.0)
  Expected in: /System/iOSSupport/System/Library/Frameworks/UIKit.framework/Versions/A/UIKit
 in /Volumes/VOLUME/Users/*/Downloads/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/iOSSupport/Library/PrivateFrameworks/IBCocoaTouchToolFoundation.framework/IBCocoaTouchToolFoundation

Last command:
_ON_QUEUE_sendMessage:toChannelReturningError:during:

Backtrace of last command:
  0   -[IBAbstractPlatformToolProxy _ON_QUEUE_sendMessage:toChannelReturningError:during:] (in IDEInterfaceBuilderKit)
  1   __74-[IBAbstractPlatformToolProxy sendMessage:toChannelReturningError:during:]_block_invoke (in IDEInterfaceBuilderKit)
  2   _dispatch_client_callout (in libdispatch.dylib)
  3   _dispatch_lane_barrier_sync_invoke_and_complete (in libdispatch.dylib)
  4   DVTDispatchSync (in DVTFoundation)
  5   -[IBAbstractPlatformToolProxy sendMessage:toChannelReturningError:during:] (in IDEInterfaceBuilderKit)
  6   -[IBAbstractPlatformToolProxy loadExtensions:] (in IDEInterfaceBuilderKit)
  7   -[IBAbstractPlatformToolProxy didLaunchWithPipeToKeepAlive:] (in IDEInterfaceBuilderKit)
  8   -[IBPlatformToolDVTTaskExecutionContext launchAndConnectToToolWithLaunchContext:toolProxyClass:proxyDelegate:shouldRaiseOnFailures:error:] (in IDEInterfaceBuilderKit)
  9   +[IBAbstractInterfaceBuilderPlatformToolManager _THREADSAFE_launchNewToolWithLaunchContext:executionContext:toolProxyClass:proxyDelegate:failureContext:requestingMethod:error:forReason:] (in IDEInterfaceBuilderKit)
 10   -[IBAbstractInterfaceBuilderPlatformToolManager launchNewToolWithDescription:error:forReason:] (in IDEInterfaceBuilderKit)
 11   -[IBCocoaTouchToolManager launchNewToolWithDescription:error:forReason:] (in IDEInterfaceBuilderCocoaTouchIntegration)
 12   -[IBAbstractInterfaceBuilderPlatformToolManager cachedToolIncrementBusyWithDescription:error:forReason:] (in IDEInterfaceBuilderKit)
 13   -[IBCocoaTouchToolManager cachedToolIncrementBusyWithDescription:error:forReason:] (in IDEInterfaceBuilderCocoaTouchIntegration)
 14   __122-[IBCocoaTouchXIBDocumentCompiler compiledKeyedObjectsDataWithMarshallingContext:archivingContext:diagnosticsBlock:error:]_block_invoke.95 (in IDEInterfaceBuilderCocoaTouchIntegration)
 15   _dispatch_client_callout (in libdispatch.dylib)
 16   _dispatch_lane_barrier_sync_invoke_and_complete (in libdispatch.dylib)
 17   DVTDispatchSync (in DVTFoundation)
 18   -[IBCocoaTouchXIBDocumentCompiler compiledKeyedObjectsDataWithMarshallingContext:archivingContext:diagnosticsBlock:error:] (in IDEInterfaceBuilderCocoaTouchIntegration)
 19   __121-[IBCocoaTouchXIBDocumentCompiler compiledPackageWithOptions:marshallingContext:archivingContext:diagnosticsBlock:error:]_block_invoke (in IDEInterfaceBuilderCocoaTouchIntegration)
 20   -[IBDocumentCompiler invokeWhileUsingSourceAsIntermediateDocument:] (in IDEInterfaceBuilderKit)
 21   -[IBDocumentCompiler invokeWithIntermediateDocumentOfTargetRuntime:alwaysCopy:block:] (in IDEInterfaceBuilderKit)
 22   -[IBCocoaTouchXIBDocumentCompiler compiledPackageWithOptions:marshallingContext:archivingContext:diagnosticsBlock:error:] (in IDEInterfaceBuilderCocoaTouchIntegration)
 23   -[IBCocoaTouchXIBDocumentCompiler compileWithOptions:error:] (in IDEInterfaceBuilderCocoaTouchIntegration)
 24   +[IBDocumentCompiler compileContentsOfDocument:options:error:] (in IDEInterfaceBuilderKit)
 25   __47-[IBDocument compiledPackageWithOptions:error:]_block_invoke (in IDEInterfaceBuilderKit)
 26   -[IBDocumentAutolayoutManager ignoreAutolayoutStatusInvalidationDuring:] (in IDEInterfaceBuilderKit)
 27   -[IBDocument compiledPackageWithOptions:error:] (in IDEInterfaceBuilderKit)
 28   -[IBDocument compileAndWriteToPath:withOptions:error:] (in IDEInterfaceBuilderKit)
 29   IBCompileDocumentForSingleTargetDevice (in ibtoold)
 30   -[IBCLIInterfaceBuilderToolPersona invokeArguments:outputDictionary:] (in ibtoold)
 31   -[IBCLIInterfaceBuilderToolPersona runSingleInvocation:outputtingToFileHandle:andVerifyingEnvironment:] (in ibtoold)
 32   IBCLIServerRunSingleInvocation (in ibtoold)
 33   __IBCLIServerRunSingleInvocationWithIODirectedAtPipesAndUnlinkOnSuccess_block_invoke_2 (in ibtoold)
 34   __IBCLIServerRunSingleInvocationWithIODirectedAtPipesAndUnlinkOnSuccess_block_invoke (in ibtoold)
 35   -[IBCLIErrorForwarder forwardErrorOutputToDescriptor:whileInvokingBlock:] (in ibtoold)
 36   IBCLIServerRunSingleInvocationWithIODirectedAtPipesAndUnlinkOnSuccess (in ibtoold)
 37   main (in ibtoold)
 38   start (in libdyld.dylib)
'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3e6b1813 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff73c35d6a objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3e6cbed4 -[NSException raise] + 9
	3   IDEInterfaceBuilderKit              0x000000010bf6bf64 -[IBAbstractPlatformToolProxy _errorByAddingAdditionalCrashInformationToError:orRaiseIfNeededOnFailure:shouldRaiseOnFailures:waitForCrashLog:] + 1462
	4   IDEInterfaceBuilderKit              0x000000010bf6b984 -[IBAbstractPlatformToolProxy errorByAddingAdditionalCrashInformationToError:orRaiseIfNeededOnFailure:] + 94
	5   IDEInterfaceBuilderKit              0x000000010bf6d639 -[IBAbstractPlatformToolProxy _ON_QUEUE_sendMessage:toChannelReturningError:during:] + 213
	6   IDEInterfaceBuilderKit              0x000000010bf6d536 __74-[IBAbstractPlatformToolProxy sendMessage:toChannelReturningError:during:]_block_invoke + 38
	7   libdispatch.dylib                   0x00007fff74f3774e _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fff74f436f5 _dispatch_lane_barrier_sync_invoke_and_complete + 60
	9   DVTFoundation                       0x000000010c9c1141 DVTDispatchSync + 208
	10  IDEInterfaceBuilderKit              0x000000010bf6d459 -[IBAbstractPlatformToolProxy sendMessage:toChannelReturningError:during:] + 237
	11  IDEInterfaceBuilderKit              0x000000010bf6d6fd -[IBAbstractPlatformToolProxy loadExtensions:] + 125
	12  IDEInterfaceBuilderKit              0x000000010bf6b025 -[IBAbstractPlatformToolProxy didLaunchWithPipeToKeepAlive:] + 336
	13  IDEInterfaceBuilderKit              0x000000010bf6959e -[IBPlatformToolDVTTaskExecutionContext launchAndConnectToToolWithLaunchContext:toolProxyClass:proxyDelegate:shouldRaiseOnFailures:error:] + 1710
	14  IDEInterfaceBuilderKit              0x000000010bd7fcc3 +[IBAbstractInterfaceBuilderPlatformToolManager _THREADSAFE_launchNewToolWithLaunchContext:executionContext:toolProxyClass:proxyDelegate:failureContext:requestingMethod:error:forReason:] + 895
	15  IDEInterfaceBuilderKit              0x000000010bd80c38 -[IBAbstractInterfaceBuilderPlatformToolManager launchNewToolWithDescription:error:forReason:] + 337
	16  IDEInterfaceBuilderCocoaTouchIntegr 0x000000011f236c32 -[IBCocoaTouchToolManager launchNewToolWithDescription:error:forReason:] + 89
	17  IDEInterfaceBuilderKit              0x000000010bd7e6df -[IBAbstractInterfaceBuilderPlatformToolManager cachedToolIncrementBusyWithDescription:error:forReason:] + 196
	18  IDEInterfaceBuilderCocoaTouchIntegr 0x000000011f236ace -[IBCocoaTouchToolManager cachedToolIncrementBusyWithDescription:error:forReason:] + 89
	19  IDEInterfaceBuilderCocoaTouCommand CompileXIB failed with a nonzero exit code
```

**Comment by sberrevoets** [comment]
Is this still relevant with newer, non-beta versions of Catalyst?

**Comment by sberrevoets** [comment]
Going to close this as I don't think this will ever work on Catalyst, since the underlying UI isn't built and alerts look quite a bit different on macOS than they do on iOS.
