### ISSUE TITLE
Allow creating an alert queue

### ISSUE THREAD

**Issue by sberrevoets** [sberrevoets/SDCAlertView#3]
The behavior of showing several alerts at a time is different from UIAlertView's

**Comment by Bartzy** [comment]
Sorry for bringing this up from 4 years ago - but is this implemented in the new `UIAlertController`-like API?

**Comment by sberrevoets** [comment]
Unfortunately it is not 😕

**Comment by Bartzy** [comment]
Thanks. Is the way to do it is via multiple `UIWindow`s?

**Comment by sberrevoets** [comment]
No the current way to do it is to present the next alert from the previous one, which might work for you but is far from ideal.

**Comment by Bartzy** [comment]
Why not with different UIWindows?

**Comment by sberrevoets** [comment]
Sure that could work as well, but is probably more work as you have to manage all these windows somehow.

**Comment by Bartzy** [comment]
Displaying the next alert from the previous one is also not very straight-forward - you'd need a queue for the next alerts, something that drains it when the presentation is done (if you'll present while a presentation is not complete you'll get an error).

**Comment by sberrevoets** [comment]
Yep for sure. Depends a bit on the use-case: if you want to be able to show to alerts right after each other I wouldn't start juggling windows, but if you have N alerts that could show at any given point you might have to write some abstractions to make it nice.

Ideally this is just part of the library but I ran into some tricky stuff and was never able to solve all problems/edge cases. Since nobody really seemed to care too much about the lack of this functionality I eventually stopped pursuing it.

**Comment by Bartzy** [comment]
It would be very nice to have as part of the library :)
My use-case is that I want to display alerts one after the other, without the user accepting any alert (meaning just blasting a bunch of alerts to the screen that the user then needs to handle/dismiss one at a time).
The thing is, is I get a notification from the system (open URL) and need to show an alert. Then after a very short while I get another one, while the first alert is still in the presentation process (but not yet presented). And then, I'm in a problem - How can I queue the 2nd alert to present immediately after the first one completed presenting?

**Comment by sberrevoets** [comment]
Yeah it’s a tough case that’s unfortunately unsupported and pretty hard to get right so I’m afraid I don’t have a good answer at the moment.
