### ISSUE TITLE
Different look for dark theme in ios 13 and ios 12

### ISSUE THREAD

**Issue by salos1982** [sberrevoets/SDCAlertView#314]
Hello,

 I'm using this great alert view. But I found an issue I cannot understand. I use a dark theme for my application. And on ios 13 it works correctly. Like on image bellow
<img width="369" alt="Screen Shot 2020-07-07 at 12 19 34" src="https://user-images.githubusercontent.com/2404581/86758100-496ab980-c04c-11ea-9141-2bc9a1b62eef.png">
But on ios 12 it looks very different
<img width="317" alt="Screen Shot 2020-07-07 at 12 24 31" src="https://user-images.githubusercontent.com/2404581/86758974-e4fc2a00-c04c-11ea-8016-e28a8557435a.png">

I do not understand why

**Comment by sberrevoets** [comment]
It's likely some change in UIKit between iOS 12 and 13, but not sure what that would be.

**Comment by salos1982** [comment]
I found reason
`var blurEffect: UIBlurEffect {
        if #available(iOS 13, *) {
            return UIBlurEffect(style: .systemMaterial)
        } else if #available(iOS 10, *) {
            return UIBlurEffect(style: .prominent)
        } else {
            return UIBlurEffect(style: .extraLight)
        }
    }
`
for ios 12 this property in AlertVisualStyle returns  `UIBlurEffect(style: .prominent)`. If replace this return to `UIBlurEffect(style: .dark)` it will show everything as I need.  However, I cannot change behaviour of this property anyhow.

**Comment by sberrevoets** [comment]
But then it would be dark even if the user has light mode set?

**Comment by salos1982** [comment]
It would be nice if it is possible to override this property. In this case, it would be possible to set up necessary behavior

**Comment by salos1982** [comment]
Could you tell me when you merge my pull request and update version?

**Comment by sberrevoets** [comment]
Handled in #315, sorry for the delay
