### ISSUE TITLE
Application tried to present modally an active controller

### ISSUE THREAD

**Issue by kmaiorini** [sberrevoets/SDCAlertView#65]
In certain views I need to display multiple alerts.  Since the update for iOS 8 I cannot seem to get this to work properly.  I am not sure if this is a bug or if I am just doing something wrong.  I keep getting 'Application tried to present modally to active controller'. 

Any help is greatly appreciated!

**Comment by sberrevoets** [comment]
I'm going to close this PR, if you still have problems feel free to reopen.
