### ISSUE TITLE
is SDCAlertViewWidth still useful when using SDCAlertController?

### ISSUE THREAD

**Issue by skydivedan** [sberrevoets/SDCAlertView#73]
(I posted this question on StackOverflow awhile back, sorry to duplicate)

I've been using SDCAlertView, and am very happy with it.

I recently updated to the latest version, which now has SDCAlertController.

In the old way, I need to add some extra views onscreen, but one of them was an extra UILabel. I would create it with a frame that had the width as "SDCAlertViewWidth" minus about 20 points (10 pt margin on each side). This was a UILabel that could have as many lines as needed (0 lines), and I would call "sizeToFit" to force it to resize itself.

"SDCAlertViewWidth" isn't available in SDCAlertController. What is the best way to do this (add in new view), under the new way of doing things?

**Comment by sberrevoets** [comment]
Sorry, I usually keep pretty good track of anything that pops up on SO, but the holidays tend to mess with that.

`SDCAlertViewWidth` is not something you need anymore. `SDCAlertController` instances have a `visualStyle` property, which has to conform to `SDCAlertControllerVisualStyle`. This protocol has a mandatory `width` property that you can use to get the width of an alert.

Hope this helps! I'll close this, but feel free to reopen if this doesn't answer your question.
