### ISSUE TITLE
Wrong animation when presenting multiple legacy alerts in succession

### ISSUE THREAD

**Issue by EvGeniyLell** [sberrevoets/SDCAlertView#79]
```objc
// try it
//--------------------
	SDCAlertView *alert = [[SDCAlertView alloc] initWithTitle:@"Title1" message:@"message1" delegate:nil cancelButtonTitle:@"Cancel" otherButtonTitles:@"Ok",nil];
	[alert setAlertViewStyle:SDCAlertViewStyleSecureTextInput];
	[alert setClickedButtonHandler:^(NSInteger buttonIndex) {
		SDCAlertView *alert = [[SDCAlertView alloc] initWithTitle:@"initWithTitle2" message:@"message2" delegate:nil cancelButtonTitle:@"Cancel" otherButtonTitles:nil];
		[alert show];
	}];
	[alert show];
```

**Comment by sberrevoets** [comment]
You're creating a local variable in your block that shadows the variable for your first alert. Does the problem persist if you rename one of the 2 variables?

**Comment by EvGeniyLell** [comment]
yes, problem remains

**Comment by EvGeniyLell** [comment]
What about this problem? it is a bug or a feature?

**Comment by EvGeniyLell** [comment]
![2015-02-06 16 02 02](https://cloud.githubusercontent.com/assets/1710383/6080609/9f7d3aa8-ae1b-11e4-9d9f-6de1d7a3a1a4.png)

**Comment by sberrevoets** [comment]
I haven't yet had the time to look into this, but based on the screenshot sequence above I'd say that is indeed a bug.

**Comment by sberrevoets** [comment]
I see the issue. `SDCAlertView` works ok on iOS 7, but not on iOS 8. You should use `SDCAlertController`, which will work on both 7 and 8 (because it uses `SDCAlertView` on iOS 7 under the hood).

**Comment by EvGeniyLell** [comment]
// try it
//--------------------
	SDCAlertController *alertController0 = [SDCAlertController alertControllerWithTitle:@"Title0"
																				message:@"message0"
																		 preferredStyle:SDCAlertControllerStyleLegacyAlert];
	[alertController0 addTextFieldWithConfigurationHandler:nil];
	[alertController0 addAction:[SDCAlertAction actionWithTitle:@"Cancel" style:SDCAlertActionStyleDefault handler:nil]];
	[alertController0 presentWithCompletion:nil];

	
	SDCAlertController *alertController1 = [SDCAlertController alertControllerWithTitle:@"Title1"
																				message:@"message1"
																		 preferredStyle:SDCAlertControllerStyleLegacyAlert];
	[alertController1 addTextFieldWithConfigurationHandler:nil];
	[alertController1 addTextFieldWithConfigurationHandler:nil];
	[alertController1 addAction:[SDCAlertAction actionWithTitle:@"OK" style:SDCAlertActionStyleDefault handler:^(SDCAlertAction *action) {
		SDCAlertController *alertController2 = [SDCAlertController alertControllerWithTitle:@"Title2"
																					message:@"message2"
																			 preferredStyle:SDCAlertControllerStyleLegacyAlert];
		[alertController2 addAction:[SDCAlertAction actionWithTitle:@"Cancel" style:SDCAlertActionStyleDefault handler:nil]];
		[alertController2 presentWithCompletion:nil];
	}]];
	[alertController1 addAction:[SDCAlertAction actionWithTitle:@"Cancel" style:SDCAlertActionStyleDefault handler:nil]];
	[alertController1 presentWithCompletion:nil];

**Comment by EvGeniyLell** [comment]
Toggle Slow animations in simulator Comand+T
video wrong animation for controller
https://www.dropbox.com/s/8g2sfx95owkqslc/SDCAlertController.mov?dl=0

**Comment by sberrevoets** [comment]
Yeah, that's a problem. I'll look into it, thanks for bringing this up!

**Comment by EvGeniyLell** [comment]
// hot fix for SDCAlertView
// in SDCAlertViewController.m
//-----
- (void)showAlert:(SDCAlertView *)alert {
	if (alert) {
		[alert becomeFirstResponder];
		[self.alertContainerView addSubview:alert];
		[self.alertContainerView layoutIfNeeded];
	}
}

**Comment by sberrevoets** [comment]
Thanks @EvGeniyLell for reporting! I was able to verify your issue and your fix seems pretty good, so that's what I went with.
