### ISSUE TITLE
Linker warning when building for iPhone simulator

### ISSUE THREAD

**Issue by gereons** [sberrevoets/SDCAlertView#80]
Starting with release 2.2, I get this warning

`ld: warning: instance method 'legacyAlertView' in category from /Users/gereon/Library/Developer/Xcode/DerivedData/NRTM-aemqjhrehqenzxfmtdikgczpmrmx/Build/Products/Debug-iphonesimulator/libPods-SDCAlertView.a(SDCAlertController.o) overrides method from class in /Users/gereon/Library/Developer/Xcode/DerivedData/NRTM-aemqjhrehqenzxfmtdikgczpmrmx/Build/Products/Debug-iphonesimulator/libPods-SDCAlertView.a(SDCAlertController.o)`

when building for the simulator. This goes away when I build for a device, or when I revert to v2.1.1

**Comment by sberrevoets** [comment]
Ah yeah, can't override methods in a category... Thanks!
