### ISSUE TITLE
Can't build with cocoapods, not latest version?

### ISSUE THREAD

**Issue by CaledoniaProject** [sberrevoets/SDCAlertView#83]
Hi I installed SDC with pods:

%> ls Pods/SDCAlertView/SDCAlertView/
./                            SDCAlertView.m                SDCAlertViewContentView.h     SDCAlertViewController.m
../                           SDCAlertViewBackgroundView.h  SDCAlertViewContentView.m
SDCAlertView.h                SDCAlertViewBackgroundView.m  SDCAlertViewController.h

Lots of things missing ... at first I thought the example in readme.md was misleading then I found the version I installed is incomplete.

Anyway cocoapods selected version 0.9 automatically, am I doing it wrongfully?

**Comment by sberrevoets** [comment]
What does your Podfile look like?

**Comment by CaledoniaProject** [comment]
Just a single line:

`pod "SDCAlertView"`

**Comment by sberrevoets** [comment]
That's really weird. 0.9 was the beta version from 1.5 years ago. Have you tried doing `pod update` recently?

**Comment by CaledoniaProject** [comment]
Never mind, I created a new project and did the same thing again, now "SDCAlertView (2.2)" is installed, looks good ...

**Comment by sberrevoets** [comment]
No problem. I just released 2.3, so you may want to update to that version. Happy coding!
