### ISSUE TITLE
Crash in iOS 7 using SDCAlertAction with attributed title

### ISSUE THREAD

**Issue by milancermak** [sberrevoets/SDCAlertView#85]
There's a crash when using the SDCAlertAction with an attributed title under iOS 7. Because the `title` property is `nil`, it crashes [when trying to add it into an array](https://github.com/sberrevoets/SDCAlertView/blob/master/SDCAlertView/Source/SDCAlertViewContentView.m#L254). It can be prevented [two levels up](https://github.com/sberrevoets/SDCAlertView/blob/master/SDCAlertView/Source/SDCAlertView.m#L539), by using `action.attributedTitle.string` instead.

Sorry that I didn't send a PR. I'm not deeply familiar with the library so there might be a better way how to fix this.

Here's at least some code to reproduce:

```objc
NSAttributedString *cancel = [[NSAttributedString alloc] initWithString:@"Cancel"];
NSAttributedString *confirm = [[NSAttributedString alloc] initWithString:@"Confirm"];

SDCAlertController *alert = [SDCAlertController alertControllerWithTitle:@"Hello"
                                                                 message:@"Go to github?"
                                                          preferredStyle:SDCAlertControllerStyleAlert];

[alert addAction:[SDCAlertAction actionWithAttributedTitle:cancel style:SDCAlertActionStyleCancel handler:nil]];
[alert addAction:[SDCAlertAction actionWithAttributedTitle:confirm style:SDCAlertActionStyleDefault handler:^(SDCAlertAction *action) {
    [UIApplication.sharedApplication openURL:[NSURL URLWithString:@"https://github.com"]];
}]];

[alert presentWithCompletion:nil];
```

**Comment by milancermak** [comment]
Looking at it a bit further, overwriting the `title` getter in `SDCAlertAction` seems to prevent the problem.

```objc
@synthesize title = _title;

// code, code, code

- (NSString *)title {
    if (self.attributedTitle) {
        return self.attributedTitle.string;
    }
    return _title;
}
```
Should I send a PR?

**Comment by sberrevoets** [comment]
I think overwriting the title in the getter is not a good idea, as that is used in other places to determine whether we should use `title` or `attributedTitle`. However, the fix you proposed [here](https://github.com/sberrevoets/SDCAlertView/blob/master/SDCAlertView/Source/SDCAlertView.m#L539) seems good to me, so go ahead and submit a PR if you want.

Thanks!
