### ISSUE TITLE
No more than 2 lines ?

### ISSUE THREAD

**Issue by aessig** [sberrevoets/SDCAlertView#89]
Hi, 
Is it normal that we can't have more than 2 lines of messages in a simple alert view (using v2.3.1), or is it a bug ? Wasn't the case on v2.3. Cheers

**Comment by sberrevoets** [comment]
That is definitely a bug. Can you show the code you use to create the alert and the result?

**Comment by aessig** [comment]
I just used your demo code with a lot of text in the message field, and I can only read two lines of text. 
```
SDCAlertController *alert = [SDCAlertController alertControllerWithTitle:@"Title"
                                                                     message:@"This is a message This is a message This is a message This is a message This is a message This is a message This is a message This is a message This is a message This is a message This is a message This is a message This is a message This is a message"
                                                              preferredStyle:SDCAlertControllerStyleAlert];
    [alert addAction:[SDCAlertAction actionWithTitle:@"OK" style:SDCAlertActionStyleDefault handler:nil]];
    [alert presentWithCompletion:nil];
```
And here is the result I get:
![alertview_error](https://cloud.githubusercontent.com/assets/8768781/6758290/5bab319e-cf37-11e4-8e6e-11b49c3b605d.png)

**Comment by sberrevoets** [comment]
I see, certainly a bug and I think it's a recent bug fix that causes this. I will revert that change and have a fix out for this soon. Thanks for reporting!

**Comment by sberrevoets** [comment]
2.3.2 should work again (except on iPad 2, apparently...)
