### ISSUE TITLE
Listening for Touches

### ISSUE THREAD

**Issue by TCWORLD** [sberrevoets/SDCAlertView#9]
In iOS6, I implemented an alert which contains a UITableView. With iOS7 clearly the default alert doesn't work. 
With your implementation I have managed to dynamically switch in SDCAlertView as the superclass if the current version is iOS7 or newer.
For most situations this works, however for tableViews, while they appear correctly on the alert, they don't seem to receive any touches - so if you try to tap on a cell, nothing happens.
I'm still early in debugging this, and it may well be something simple with my implementation. I thought it best though to check with you to see if this is a known issue and/or if there is a work around for it.

**Comment by edenfisher** [comment]
Hey, I have similar problem too
my subview is not clickable
