### ISSUE TITLE
shouldDismisBlock

### ISSUE THREAD

**Issue by josemantilla26** [sberrevoets/SDCAlertView#90]
alert.shouldDismissBlock = ^ BOOL(SDCAlertAction *action) {     return NO; }; is not getting called on IOS7

**Comment by sberrevoets** [comment]
IIRC, this was fixed in a recent update. Have you tried updating SDCAlertView to the latest version?

**Comment by josemantilla26** [comment]
I just installed using pod install in a blank project, do i need to do something else.

JD

**Comment by sberrevoets** [comment]
What does your Podfile look like?

**Comment by sberrevoets** [comment]
Actually, I looked at the code and that was never passed on. I've issued a fix. Can you verify that it works?

**Comment by fnxpt** [comment]
For me its crashing if you dont have shouldDismissBlock defined

**Comment by sberrevoets** [comment]
Yeah, that was stupid. I've fixed your merge and will update CocoaPods right away as well.
