### ISSUE TITLE
Layout loop / hang in some cases

### ISSUE THREAD

**Issue by virusman** [sberrevoets/SDCAlertView#91]
We're experiencing hangs similar to what was described in #87: the app hangs, trying to layoutSubviews inside its ScrollView indefinitely. Happens on all devices.
I've created a repo with the test case: https://github.com/virusman/SDCAlertViewLayoutBugCase
It only happens in specific circumstances: when I change the font, font size or even the message, the bug disappears, but due to its unpredictable nature it might very well appear somewhere else, so it's better to try to figure out a solution for this.

**Comment by sberrevoets** [comment]
Completely agree, but unfortunately I'm pretty clueless as to what causes the issue. Does it happen on all devices and both iOS 7 and 8?

**Comment by virusman** [comment]
SDCAlertController only works on iOS 8, so the legacy one probably won't have the same problem. However, I have adapted SDCAlertController to work on iOS 7 in my branch, and it doesn't hang on iOS 7.

**Comment by sberrevoets** [comment]
Hmm, this seems tricky. Especially with the state that iOS 8 is in, it's very hard to determine whether I am not correctly understanding how the layout system works, or if there's just a bug in iOS 8 I'll have to work around. Do you know of a workaround in the mean time?

I am interested in seeing your branch with the back port of the iOS 8 alert. I can't guarantee I'll merge it in (because it seems like that wouldn't be what most people want), but I'm certainly interested in seeing how you did it.

**Comment by virusman** [comment]
The layout system needs at least 3 layout passes to draw everything correctly in SDCAlertControllerScrollView. The workaround is simple, but doesn't look very nice:
```objective-c
@property (nonatomic) NSInteger layoutPasses;
```
```objective-c
- (void)layoutSubviews {
	[super layoutSubviews];
    if (self.layoutPasses < 5) {
        [self invalidateIntrinsicContentSize];
        [super layoutSubviews];
        self.layoutPasses++;
    }
}
```
Basically, this limits layout passes to 4 to avoid an infinite loop.

**Comment by sberrevoets** [comment]
Hmm yeah, that may work for a limited number of alerts, but it's too fragile to ship. I'm going to take some time this week to figure out if there's something cleaner. I'll keep you posted.

**Comment by DarthMike** [comment]
@sberrevoets Any updates on this issue? I've seen this happening in our app on iOS 8.3, iPhone 6+ and zoomed mode :open_mouth:

**Comment by sberrevoets** [comment]
Unfortunately, no. The different behavior on different iOS version and devices makes, and a documentation that doesn't mention this at all makes this a difficult problem to tackle. However, this is the highest priority issue for the library, so any time I can spend on it I will.

**Comment by sberrevoets** [comment]
@virusman, @DarthMike I think I finally solved this issue. Please check out this branch: https://github.com/sberrevoets/SDCAlertView/tree/infinite-loop-fix

See the commit in that branch for more details. I tried this on an iPad 2/iPhone 6 at iOS 8.2 & 8.3. It works on all those platforms. Can you please see if this does indeed fix the problem? Thanks for your patience on this.

**Comment by DarthMike** [comment]
@sberrevoets Nice! :tada: I will check today

**Comment by giantroboticcat** [comment]
Was having the same issue, the above change resolved the problem in my case.

**Comment by DarthMike** [comment]
@sberrevoets Seems to work now. Thanks!

**Comment by sberrevoets** [comment]
Great, just merged this :100:
