### ISSUE TITLE
No way to disable the motion parallax effect?

### ISSUE THREAD

**Issue by mbuchetics** [sberrevoets/SDCAlertView#93]
Is there a way to control the motion parallax effect when I tilt the phone? I couldn't find a setting.

**Comment by sberrevoets** [comment]
There isn't currently. Any particular reason you want to turn it off? The alert is supposed to stick as much to the original alert as possible.

I could add a `BOOL` property, but I try to keep to public API small so it's easy to interact with. However, if you have a compelling reason you want to turn it off, I'm not strongly opposed to adding it anyway.

**Comment by sberrevoets** [comment]
Actually, I just realized that you can subclass `SDCAlertControllerDefaultVisualStyle` and set the `parallax` property to `(0, 0)`. That should accomplish what you want.

Closing this, but if that's not sufficient feel free to reopen.

**Comment by mbuchetics** [comment]
Thank you!
