### ISSUE TITLE
[question] SDCAlertController support for UIAlertControllerStyleActionSheet

### ISSUE THREAD

**Issue by jeloagnasin** [sberrevoets/SDCAlertView#96]
Is there a support for `UIAlertControllerStyleActionSheet`?

**Comment by sberrevoets** [comment]
Unfortunately, no. Initially, I wrote `SDCAlertView` to have a more or less supported way to add custom views to an alert. That's not a very common thing to do with action sheets, so I never ported that behavior.

Any particular reason you want it?

**Comment by jeloagnasin** [comment]
Since `UIAlertView` and `UIActionSheet` are deprecated in favor of `UIAlertController` in iOS 8.0, I was looking for a library that can display `UIAlertView` and `UIActionSheet` both for iOS 7.0 and 8.0. A library that, in effect, will mimic `UIAlertController` but will allow it to work on iOS 7.0. So I thought, your `SDCAlertController` would have done that.

Thanks for your quick response!

**Comment by sberrevoets** [comment]
Got it. I've heard that argument before, but because of how action sheets are displayed on iPad, I think it'll be a lot more difficult to copy that behavior. But who knows, maybe one of these days I find myself with a bunch of free time :)

Thanks for your feedback I'll keep it in mind!
