### ISSUE TITLE
Wrong action triggered with SDCAlertController on iOS7

### ISSUE THREAD

**Issue by hac-git** [sberrevoets/SDCAlertView#97]
The indexing between buttons and actions can break on iOS 7 when using styles for the actions (SDCAlertActionStyleCancel or SDCAlertActionStyleRecommended). If actions are added to the alert in wrong order, this can cause wrong action handler to trigger. Does not happen on iOS 8.

Example code to replicate:
```objectivec
        SDCAlertController *alert = [SDCAlertController alertControllerWithTitle:@"Title"
                                                                         message:@"Message"
                                                                  preferredStyle:SDCAlertControllerStyleAlert];
        SDCAlertAction *defaultAction = [SDCAlertAction actionWithTitle:@"Default"
                                                                  style:SDCAlertActionStyleDefault
                                                                handler:^(SDCAlertAction *action) {
                                                                    NSLog(@"Pressed default. Action title: %@", action.title);
                                                                }];
        SDCAlertAction *cancelAction = [SDCAlertAction actionWithTitle:@"Cancel"
                                                                 style:SDCAlertActionStyleCancel
                                                               handler:^(SDCAlertAction *action) {
                                                                   NSLog(@"Pressed cancel. Action title: %@", action.title);
                                                               }];
        [alert addAction:defaultAction];
        [alert addAction:cancelAction];
        [alert presentWithCompletion:nil];
```
If the order of adding actions to alerts is changed, the correct action will be triggered.

**Comment by sberrevoets** [comment]
Hmm, yep, it doesn't account for a cancel button index that's different than the index in which it was added. I'll see if I can find a fix this weekend.

An obvious workaround until I then is to add buttons in a different order. Hopefully that still works with your iOS 8 design.

**Comment by hac-git** [comment]
I needed to keep the button order so I worked around the issue by setting all actions with default style and using attributed title for the actions to set the font bold.

BTW. Looks like alert.view.tintColor doesn't have any effect in iOS7, button text color does change in iOS8. Same problem if I try to change the button text color in attributed title for action. But perhaps that should be an issue of its own.

**Comment by sberrevoets** [comment]
That's not a very convenient workaround. It's on my radar, thanks for reporting.

The other issue is likely related to how `tintColor` works. I think your best bet there would be to just use `alertController.legacyAlertView` and manually apply a tint color. Since the old legacy alert is presented in a separate window, the tint color mechanism doesn't work too well anymore. If you continue to have problems, please create another issue so it's easier to keep track of.

**Comment by vocaro** [comment]
Here's the workaround I used:

* Add Cancel button first, then OK button
* For the Cancel button, use SDCAlertActionStyleDefault
* For the OK button, use SDCAlertActionStyleRecommended on iOS 8 and SDCAlertActionStyleDefault on iOS 7

**Comment by sberrevoets** [comment]
I just fixed this bug. Let me know if you have any more problems with this.
